const fs = require('fs');
const path = require('path');

const content = fs.readFileSync(path.join(__dirname, 'src', 'raw_data.tsv'), 'utf8');

// Parse TSV rows while correctly handling quotes and multiline cells
function parseTSVRows(text) {
  const rows = [];
  let currentRow = [];
  let currentField = "";
  let insideQuotes = false;

  for (let i = 0; i < text.length; i++) {
    const char = text[i];
    const nextChar = text[i + 1];

    if (insideQuotes) {
      if (char === '"') {
        if (nextChar === '"') {
          currentField += '"';
          i++;
        } else {
          insideQuotes = false;
        }
      } else {
        currentField += char;
      }
    } else {
      if (char === '"') {
        insideQuotes = true;
      } else if (char === '\t') {
        currentRow.push(currentField.trim());
        currentField = "";
      } else if (char === '\r' || char === '\n') {
        if (char === '\r' && nextChar === '\n') {
          i++;
        }
        currentRow.push(currentField.trim());
        rows.push(currentRow);
        currentRow = [];
        currentField = "";
      } else {
        currentField += char;
      }
    }
  }
  if (currentField || currentRow.length > 0) {
    currentRow.push(currentField.trim());
    rows.push(currentRow);
  }
  return rows.filter(r => r.length > 0 && r.some(cell => cell.length > 0));
}

// Split content by our markers
const parts = content.split(/=== [A-Z]+ ===/);
const sections = content.match(/=== [A-Z]+ ===/g);

let talanganRaw = "";
let hutangRaw = "";
let transaksiRaw = "";

if (sections && parts) {
  for (let idx = 0; idx < sections.length; idx++) {
    const sectionName = sections[idx];
    const rawText = parts[idx + 1] || "";
    if (sectionName.includes("TALANGAN")) talanganRaw = rawText;
    if (sectionName.includes("HUTANG")) hutangRaw = rawText;
    if (sectionName.includes("TRANSAKSI")) transaksiRaw = rawText;
  }
}

function processSection(rawText, type) {
  const allRows = parseTSVRows(rawText);
  if (allRows.length < 2) return [];
  
  const headers = allRows[0].map(h => h.toLowerCase().trim());
  const records = [];

  for (let i = 1; i < allRows.length; i++) {
    const row = allRows[i];
    // Skip placeholder or empty header lines
    if (row[0] === 'id') continue;
    
    // Direct index matches to safely build objects
    const obj = {};
    headers.forEach((header, colIdx) => {
      if (row[colIdx] !== undefined) {
        obj[header] = row[colIdx];
      } else {
        obj[header] = "";
      }
    });

    // Formatting fields
    if (obj.jumlah) {
      obj.jumlah = Number(obj.jumlah.replace(/[^0-9.-]+/g, ""));
    }
    if (obj.id_anggaran) {
      obj.id_anggaran = Number(obj.id_anggaran);
    }
    if (obj.id_anggaran_pemberi) {
      obj.id_anggaran_pemberi = Number(obj.id_anggaran_pemberi);
    }
    if (obj.id_anggaran_penerima) {
      obj.id_anggaran_penerima = Number(obj.id_anggaran_penerima);
    }

    // Convert date timestamp or dates if empty
    if (!obj.tanggal) {
      obj.tanggal = "2026-06-01";
    }

    // Clean up empty optional fields
    if (obj.ref_id === "") delete obj.ref_id;
    if (obj.bukti === "") delete obj.bukti;
    
    // Timestamp ISO format
    let timestampIso = new Date().toISOString();
    if (obj.timestamp) {
      try {
        const d = new Date(obj.timestamp);
        if (!isNaN(d.getTime())) {
          timestampIso = d.toISOString();
        }
      } catch (e) {}
    }
    obj.timestamp = timestampIso;

    // Type casting
    if (type === 'transaksi') {
      if (obj.tipe !== 'Pemasukan' && obj.tipe !== 'Pengeluaran') {
        obj.tipe = 'Pengeluaran';
      }
    } else if (type === 'talangan' || type === 'hutang') {
      if (obj.status !== 'Lunas' && obj.status !== 'Belum Lunas') {
        obj.status = 'Belum Lunas';
      }
    }

    records.push(obj);
  }
  return records;
}

const talanganList = processSection(talanganRaw, 'talangan');
const hutangList = processSection(hutangRaw, 'hutang');
const transaksiList = processSection(transaksiRaw, 'transaksi');

const outputCode = `/**
 * Pre-populated master databases from the Google Sheets spreadsheet dump.
 * Autogenerated by AI script execution.
 */
import { Transaksi, Talangan, Hutang } from "./types";

export const INITIAL_TRANSAKSI: Transaksi[] = ${JSON.stringify(transaksiList, null, 2)};

export const INITIAL_TALANGAN: Talangan[] = ${JSON.stringify(talanganList, null, 2)};

export const INITIAL_HUTANG: Hutang[] = ${JSON.stringify(hutangList, null, 2)};
`;

fs.writeFileSync(path.join(__dirname, 'src', 'initialDatabase.ts'), outputCode, 'utf8');
console.log(`Success! Parsed ${transaksiList.length} Transaksi, ${talanganList.length} Talangan, and ${hutangList.length} Hutang.`);
