/**
 * Pre-populated master databases from the Google Sheets spreadsheet dump.
 * Autogenerated by AI script execution.
 */
import { Transaksi, Talangan, Hutang } from "./types";

export const INITIAL_TRANSAKSI: Transaksi[] = [
  {
    "id": "TX-C55F449D",
    "tanggal": "2026-01-15",
    "tipe": "Pemasukan",
    "id_anggaran": 4,
    "jumlah": 52200000,
    "keterangan": "Penghasilan Tetap Perangkat Desa 4 orang x 2.175.000 x 6 bulan",
    "timestamp": "2026-06-05T17:07:32.000Z"
  },
  {
    "id": "TX-1575A1B0",
    "tanggal": "2026-01-15",
    "tipe": "Pemasukan",
    "id_anggaran": 5,
    "jumlah": 34800000,
    "keterangan": "Pengganti Hak Garap Bengkok 3 B",
    "timestamp": "2026-06-05T17:08:19.000Z"
  },
  {
    "id": "TX-FA79C034",
    "tanggal": "2026-01-15",
    "tipe": "Pemasukan",
    "id_anggaran": 11,
    "jumlah": 2000000,
    "keterangan": "Honor kemit Bulan Januari",
    "timestamp": "2026-06-05T17:09:01.000Z"
  },
  {
    "id": "TX-E922DD2E",
    "tanggal": "2026-01-15",
    "tipe": "Pemasukan",
    "id_anggaran": 10,
    "jumlah": 19000000,
    "keterangan": "Honor Juru Kunci Makam",
    "timestamp": "2026-06-05T17:09:28.000Z"
  },
  {
    "id": "TX-94D26C2B",
    "tanggal": "2026-01-15",
    "tipe": "Pemasukan",
    "id_anggaran": 27,
    "jumlah": 36900000,
    "keterangan": "Tunjangan BPD PAD",
    "timestamp": "2026-06-05T17:10:07.000Z"
  },
  {
    "id": "TX-CA9698BF",
    "tanggal": "2026-01-15",
    "tipe": "Pemasukan",
    "id_anggaran": 22,
    "jumlah": 26900000,
    "keterangan": "Insentif RT/RW",
    "timestamp": "2026-06-05T17:10:48.000Z"
  },
  {
    "id": "TX-CFCD2D68",
    "tanggal": "2026-01-17",
    "tipe": "Pengeluaran",
    "id_anggaran": 11,
    "jumlah": 2000000,
    "keterangan": "Honor Kemit Bulan Januari",
    "timestamp": "2026-06-05T17:11:43.000Z"
  },
  {
    "id": "TX-2FBAE912",
    "tanggal": "2026-01-17",
    "tipe": "Pengeluaran",
    "id_anggaran": 10,
    "jumlah": 19000000,
    "keterangan": "Honor Juru Kunci Makam Desa",
    "timestamp": "2026-06-05T17:13:09.000Z"
  },
  {
    "id": "TX-51A688CC",
    "tanggal": "2026-01-17",
    "tipe": "Pengeluaran",
    "id_anggaran": 27,
    "jumlah": 36900000,
    "keterangan": "Tunjangan Keudukan BP PAD",
    "timestamp": "2026-06-05T17:13:51.000Z"
  },
  {
    "id": "TX-4557FEFA",
    "tanggal": "2026-01-17",
    "tipe": "Pengeluaran",
    "id_anggaran": 22,
    "jumlah": 26900000,
    "keterangan": "Insentif RT/RW",
    "timestamp": "2026-06-05T17:14:28.000Z"
  },
  {
    "id": "TX-C41D6589",
    "tanggal": "2026-01-17",
    "tipe": "Pengeluaran",
    "id_anggaran": 4,
    "jumlah": 225000,
    "keterangan": "Honor Pengambilan Uang PAD Tahap I Tangguh, Mamuri",
    "timestamp": "2026-06-05T17:16:14.000Z"
  },
  {
    "id": "TX-E1B74202",
    "tanggal": "2026-01-17",
    "tipe": "Pengeluaran",
    "id_anggaran": 4,
    "jumlah": 1500000,
    "keterangan": "Pemberian Pinjaman Hutang ke Pribadi: Keperluan Mendadak",
    "ref_id": "HT-15C54FC4",
    "timestamp": "2026-06-05T17:17:48.000Z"
  },
  {
    "id": "TX-32CC23DB",
    "tanggal": "2026-01-17",
    "tipe": "Pengeluaran",
    "id_anggaran": 4,
    "jumlah": 1000000,
    "keterangan": "Pemberian Pinjaman Hutang ke Pribadi: Keperluan Mendadak",
    "ref_id": "HT-6B4B4596",
    "timestamp": "2026-06-05T17:19:10.000Z"
  },
  {
    "id": "TX-7FAD32B4",
    "tanggal": "2026-01-17",
    "tipe": "Pemasukan",
    "id_anggaran": 60,
    "jumlah": 2000000,
    "keterangan": "Penerimaan Talangan dari Anggaran ID 4: Rehab Mushola Tahsinul Ahlaq",
    "ref_id": "TL-C97CE0AD",
    "timestamp": "2026-06-05T17:20:22.000Z"
  },
  {
    "id": "TX-516312F5",
    "tanggal": "2026-01-17",
    "tipe": "Pengeluaran",
    "id_anggaran": 60,
    "jumlah": 2000000,
    "keterangan": "Penggunaan Dana Talangan dari Anggaran ID 4: Rehab Mushola Tahsinul Ahlaq",
    "ref_id": "TL-C97CE0AD",
    "timestamp": "2026-06-05T17:20:23.000Z"
  },
  {
    "id": "TX-E8D2ED8F",
    "tanggal": "2026-01-17",
    "tipe": "Pengeluaran",
    "id_anggaran": 4,
    "jumlah": 2000000,
    "keterangan": "Pemberian Talangan ke Anggaran ID 60: Rehab Mushola Tahsinul Ahlaq",
    "ref_id": "TL-C97CE0AD",
    "timestamp": "2026-06-05T17:20:23.000Z"
  },
  {
    "id": "TX-D2C40E41",
    "tanggal": "2025-01-17",
    "tipe": "Pengeluaran",
    "id_anggaran": 5,
    "jumlah": 34800000,
    "keterangan": "Pengganti Hak Garap Bengkok 3B",
    "timestamp": "2026-06-05T17:24:00.000Z"
  },
  {
    "id": "TX-A8B207F1",
    "tanggal": "2026-01-14",
    "tipe": "Pengeluaran",
    "id_anggaran": 4,
    "jumlah": 45000000,
    "keterangan": "Pemberian Pinjaman Hutang ke Pribadi: -",
    "ref_id": "HT-C62B693D",
    "timestamp": "2026-06-05T17:24:45.000Z"
  },
  {
    "id": "TX-A2CFB8B7",
    "tanggal": "2026-01-17",
    "tipe": "Pengeluaran",
    "id_anggaran": 4,
    "jumlah": 475000,
    "keterangan": "Pemberian Pinjaman Hutang ke Pribadi: Upah TUKANG Nyi Tosa",
    "ref_id": "HT-A35E4CBF",
    "timestamp": "2026-06-05T17:26:42.000Z"
  },
  {
    "id": "TX-04AB0E6E",
    "tanggal": "2026-01-17",
    "tipe": "Pengeluaran",
    "id_anggaran": 4,
    "jumlah": 1000000,
    "keterangan": "Pemberian Pinjaman Hutang ke Pribadi: Darurat",
    "ref_id": "HT-9E5F126E",
    "timestamp": "2026-06-05T17:27:10.000Z"
  },
  {
    "id": "TX-F481CE92",
    "tanggal": "2026-02-04",
    "tipe": "Pemasukan",
    "id_anggaran": 72,
    "jumlah": 21450000,
    "keterangan": "PENERIMAAN DARI PTSL",
    "timestamp": "2026-06-05T17:35:46.000Z"
  },
  {
    "id": "TX-6DEE22DD",
    "tanggal": "2026-03-26",
    "tipe": "Pemasukan",
    "id_anggaran": 13,
    "jumlah": 14867280,
    "keterangan": "LANGGANAN LISTRIK",
    "timestamp": "2026-06-05T17:46:55.000Z"
  },
  {
    "id": "TX-2C804719",
    "tanggal": "2026-03-26",
    "tipe": "Pemasukan",
    "id_anggaran": 19,
    "jumlah": 18600000,
    "keterangan": "Tunjangan BPD Tahap I",
    "timestamp": "2026-06-05T17:47:36.000Z"
  },
  {
    "id": "TX-08269AA6",
    "tanggal": "2026-03-14",
    "tipe": "Pemasukan",
    "id_anggaran": 12,
    "jumlah": 32000000,
    "keterangan": "SETOR HASIL SEWA KIOS DARI H.UDIN",
    "timestamp": "2026-06-05T17:48:16.000Z"
  },
  {
    "id": "TX-105176DD",
    "tanggal": "2026-04-28",
    "tipe": "Pemasukan",
    "id_anggaran": 71,
    "jumlah": 3600000,
    "keterangan": "DANA BLT DD Triwulan I",
    "timestamp": "2026-06-05T17:49:05.000Z"
  },
  {
    "id": "TX-5EA3E0E9",
    "tanggal": "2026-04-28",
    "tipe": "Pemasukan",
    "id_anggaran": 49,
    "jumlah": 20000000,
    "keterangan": "Sewa Wayang Mapagsri",
    "timestamp": "2026-06-05T17:49:38.000Z"
  },
  {
    "id": "TX-5D2817ED",
    "tanggal": "2026-04-28",
    "tipe": "Pemasukan",
    "id_anggaran": 50,
    "jumlah": 5000000,
    "keterangan": "Konsumsi Wayang",
    "timestamp": "2026-06-05T17:50:07.000Z"
  },
  {
    "id": "TX-5E5AD366",
    "tanggal": "2026-04-28",
    "tipe": "Pemasukan",
    "id_anggaran": 48,
    "jumlah": 3600000,
    "keterangan": "Babinsa dan Babin Kamtibmas",
    "timestamp": "2026-06-05T17:50:37.000Z"
  },
  {
    "id": "TX-D324B9FB",
    "tanggal": "2026-04-28",
    "tipe": "Pemasukan",
    "id_anggaran": 31,
    "jumlah": 37920000,
    "keterangan": "Puskesos Honor RT",
    "timestamp": "2026-06-05T17:51:11.000Z"
  },
  {
    "id": "TX-86551ED7",
    "tanggal": "2026-04-28",
    "tipe": "Pemasukan",
    "id_anggaran": 34,
    "jumlah": 15000000,
    "keterangan": "Pengembangan Sistem Informasi Desa",
    "timestamp": "2026-06-05T17:51:43.000Z"
  },
  {
    "id": "TX-56A2D9BE",
    "tanggal": "2026-04-28",
    "tipe": "Pemasukan",
    "id_anggaran": 61,
    "jumlah": 1500000,
    "keterangan": "Insentif Guru Ngaji (PBK)",
    "timestamp": "2026-06-05T17:52:16.000Z"
  },
  {
    "id": "TX-A2EC51D4",
    "tanggal": "2026-04-28",
    "tipe": "Pemasukan",
    "id_anggaran": 38,
    "jumlah": 14400000,
    "keterangan": "Honor Guru TK",
    "timestamp": "2026-06-05T17:52:40.000Z"
  },
  {
    "id": "TX-3511AC95",
    "tanggal": "2026-04-28",
    "tipe": "Pemasukan",
    "id_anggaran": 39,
    "jumlah": 81960000,
    "keterangan": "Posyandu",
    "timestamp": "2026-06-05T17:53:44.000Z"
  },
  {
    "id": "TX-95177118",
    "tanggal": "2026-04-28",
    "tipe": "Pemasukan",
    "id_anggaran": 46,
    "jumlah": 18000000,
    "keterangan": "Honor Petugas TPS",
    "timestamp": "2026-06-05T17:54:18.000Z"
  },
  {
    "id": "TX-E9D8474C",
    "tanggal": "2026-04-28",
    "tipe": "Pemasukan",
    "id_anggaran": 47,
    "jumlah": 8393600,
    "keterangan": "Sarpras TPS",
    "timestamp": "2026-06-05T17:54:57.000Z"
  },
  {
    "id": "TX-39A786CA",
    "tanggal": "2026-04-28",
    "tipe": "Pemasukan",
    "id_anggaran": 59,
    "jumlah": 4000000,
    "keterangan": "Masjid Nurul Huda",
    "timestamp": "2026-06-05T17:55:55.000Z"
  },
  {
    "id": "TX-B0DCAD7C",
    "tanggal": "2026-04-28",
    "tipe": "Pemasukan",
    "id_anggaran": 60,
    "jumlah": 2000000,
    "keterangan": "Mushola Tahsinul Ahlaq",
    "timestamp": "2026-06-05T17:56:23.000Z"
  },
  {
    "id": "TX-EEDB8A07",
    "tanggal": "2026-04-28",
    "tipe": "Pemasukan",
    "id_anggaran": 23,
    "jumlah": 11200000,
    "keterangan": "OP Pemdes Bersumber DDS",
    "timestamp": "2026-06-05T17:57:02.000Z"
  },
  {
    "id": "TX-0B1F822C",
    "tanggal": "2026-05-05",
    "tipe": "Pemasukan",
    "id_anggaran": 28,
    "jumlah": 170917,
    "keterangan": "Sarpras PAD",
    "timestamp": "2026-06-05T17:59:10.000Z"
  },
  {
    "id": "TX-9B3E7A62",
    "tanggal": "2026-05-05",
    "tipe": "Pemasukan",
    "id_anggaran": 11,
    "jumlah": 2000000,
    "keterangan": "Honor Kemit",
    "timestamp": "2026-06-05T18:00:01.000Z"
  },
  {
    "id": "TX-B011FB1C",
    "tanggal": "2026-06-02",
    "tipe": "Pemasukan",
    "id_anggaran": 12,
    "jumlah": 2000000,
    "keterangan": "SETOR H UDIN SEWA PASAR",
    "timestamp": "2026-06-05T18:00:43.000Z"
  },
  {
    "id": "TX-EA401171",
    "tanggal": "2026-06-05",
    "tipe": "Pemasukan",
    "id_anggaran": 12,
    "jumlah": 1000000,
    "keterangan": "SETOR H UDIN SEWA PASAR",
    "timestamp": "2026-06-05T18:01:51.000Z"
  },
  {
    "id": "TX-951EB0E0",
    "tanggal": "2026-03-26",
    "tipe": "Pengeluaran",
    "id_anggaran": 13,
    "jumlah": 1850000,
    "keterangan": "Langganan Listrik dan Internet Bulan Januari",
    "timestamp": "2026-06-05T18:04:41.000Z"
  },
  {
    "id": "TX-1975B7C2",
    "tanggal": "2026-03-26",
    "tipe": "Pengeluaran",
    "id_anggaran": 13,
    "jumlah": 1650000,
    "keterangan": "Langganan Listrik dan Internet Bulan Februari",
    "timestamp": "2026-06-05T18:05:18.000Z"
  },
  {
    "id": "TX-F37BEC5F",
    "tanggal": "2026-03-26",
    "tipe": "Pengeluaran",
    "id_anggaran": 13,
    "jumlah": 1700000,
    "keterangan": "Langganan Listrik dan Internet Bulan Maret",
    "timestamp": "2026-06-05T18:05:59.000Z"
  },
  {
    "id": "TX-AC3D40CF",
    "tanggal": "2026-03-26",
    "tipe": "Pemasukan",
    "id_anggaran": 7,
    "jumlah": 430000,
    "keterangan": "Penerimaan Talangan dari Anggaran ID 13: ATK ( Persiapan Zakat Fitrah Plastik Waring DLL 230.000 dan Upah Pengambilan ADD 200.000)",
    "ref_id": "TL-6A32993C",
    "timestamp": "2026-06-05T18:08:25.000Z"
  },
  {
    "id": "TX-7A72871A",
    "tanggal": "2026-03-26",
    "tipe": "Pengeluaran",
    "id_anggaran": 7,
    "jumlah": 430000,
    "keterangan": "Penggunaan Dana Talangan dari Anggaran ID 13: ATK (  Persiapan Zakat Fitrah Plastik Waring DLL 230.000 dan Upah Pengambilan ADD 200.000l)",
    "ref_id": "TL-6A32993C",
    "timestamp": "2026-06-05T18:08:26.000Z"
  },
  {
    "id": "TX-73928985",
    "tanggal": "2026-03-26",
    "tipe": "Pengeluaran",
    "id_anggaran": 13,
    "jumlah": 430000,
    "keterangan": "Pemberian Talangan ke Anggaran ID 7: ATK (  Persiapan Zakat Fitrah Plastik Waring DLL 230.000 dan Upah Pengambilan ADD 200.000)",
    "ref_id": "TL-6A32993C",
    "timestamp": "2026-06-05T18:08:26.000Z"
  },
  {
    "id": "TX-2F54156E",
    "tanggal": "2026-03-28",
    "tipe": "Pemasukan",
    "id_anggaran": 7,
    "jumlah": 1500000,
    "keterangan": "Penerimaan Talangan dari Anggaran ID 13: ATK (Baja Pupr  500.000 dan Urunan Pisah Sambut Camat 1.000.000)",
    "ref_id": "TL-3EAEAC12",
    "timestamp": "2026-06-05T18:09:30.000Z"
  },
  {
    "id": "TX-72A3C810",
    "tanggal": "2026-03-28",
    "tipe": "Pengeluaran",
    "id_anggaran": 7,
    "jumlah": 1500000,
    "keterangan": "Penggunaan Dana Talangan dari Anggaran ID 13: ATK  (Baja Pupr  500.000 dan Urunan Pisah Sambut Camat 1.000.000)",
    "ref_id": "TL-3EAEAC12",
    "timestamp": "2026-06-05T18:09:31.000Z"
  },
  {
    "id": "TX-74B1FCCB",
    "tanggal": "2026-03-28",
    "tipe": "Pengeluaran",
    "id_anggaran": 13,
    "jumlah": 1500000,
    "keterangan": "Pemberian Talangan ke Anggaran ID 7: ATK  (Baja Pupr  500.000 dan Urunan Pisah Sambut Camat 1.000.000)",
    "ref_id": "TL-3EAEAC12",
    "timestamp": "2026-06-05T18:09:31.000Z"
  },
  {
    "id": "TX-2717766E",
    "tanggal": "2026-01-04",
    "tipe": "Pemasukan",
    "id_anggaran": 47,
    "jumlah": 700000,
    "keterangan": "Penerimaan Talangan dari Anggaran ID 13: Solar Beco (Saep)",
    "ref_id": "TL-DF000F9A",
    "timestamp": "2026-06-05T18:12:15.000Z"
  },
  {
    "id": "TX-838162FD",
    "tanggal": "2026-01-04",
    "tipe": "Pengeluaran",
    "id_anggaran": 47,
    "jumlah": 700000,
    "keterangan": "Penggunaan Dana Talangan dari Anggaran ID 13: Solar Beco (Saep)",
    "ref_id": "TL-DF000F9A",
    "timestamp": "2026-06-05T18:12:16.000Z"
  },
  {
    "id": "TX-6BC56FA9",
    "tanggal": "2026-01-04",
    "tipe": "Pengeluaran",
    "id_anggaran": 13,
    "jumlah": 700000,
    "keterangan": "Pemberian Talangan ke Anggaran ID 47: Solar Beco (Saep)",
    "ref_id": "TL-DF000F9A",
    "timestamp": "2026-06-05T18:12:17.000Z"
  },
  {
    "id": "TX-4DFF2652",
    "tanggal": "2026-04-01",
    "tipe": "Pemasukan",
    "id_anggaran": 45,
    "jumlah": 1300000,
    "keterangan": "Penerimaan Talangan dari Anggaran ID 13: Pengurugan Pasar Desa",
    "ref_id": "TL-68121E8E",
    "timestamp": "2026-06-05T18:14:02.000Z"
  },
  {
    "id": "TX-5BA98CD7",
    "tanggal": "2026-04-01",
    "tipe": "Pengeluaran",
    "id_anggaran": 45,
    "jumlah": 1300000,
    "keterangan": "Penggunaan Dana Talangan dari Anggaran ID 13: Pengurugan Pasar Desa",
    "ref_id": "TL-68121E8E",
    "timestamp": "2026-06-05T18:14:03.000Z"
  },
  {
    "id": "TX-10AB14D6",
    "tanggal": "2026-04-01",
    "tipe": "Pengeluaran",
    "id_anggaran": 13,
    "jumlah": 1300000,
    "keterangan": "Pemberian Talangan ke Anggaran ID 45: Pengurugan Pasar Desa",
    "ref_id": "TL-68121E8E",
    "timestamp": "2026-06-05T18:14:03.000Z"
  },
  {
    "id": "TX-D072C9E5",
    "tanggal": "2026-04-01",
    "tipe": "Pemasukan",
    "id_anggaran": 9,
    "jumlah": 300000,
    "keterangan": "Penerimaan Talangan dari Anggaran ID 13: Pengharum Ruangan",
    "ref_id": "TL-A8F269A9",
    "timestamp": "2026-06-05T18:16:10.000Z"
  },
  {
    "id": "TX-BE7CCC30",
    "tanggal": "2026-04-01",
    "tipe": "Pengeluaran",
    "id_anggaran": 9,
    "jumlah": 300000,
    "keterangan": "Penggunaan Dana Talangan dari Anggaran ID 13: Pengharum Ruangan",
    "ref_id": "TL-A8F269A9",
    "timestamp": "2026-06-05T18:16:10.000Z"
  },
  {
    "id": "TX-7C8FF8CA",
    "tanggal": "2026-04-01",
    "tipe": "Pengeluaran",
    "id_anggaran": 13,
    "jumlah": 300000,
    "keterangan": "Pemberian Talangan ke Anggaran ID 9: Pengharum Ruangan",
    "ref_id": "TL-A8F269A9",
    "timestamp": "2026-06-05T18:16:11.000Z"
  },
  {
    "id": "TX-67C8B05E",
    "tanggal": "2026-04-01",
    "tipe": "Pengeluaran",
    "id_anggaran": 13,
    "jumlah": 3500000,
    "keterangan": "Pemberian Pinjaman Hutang ke Pribadi: Dana Mendesak",
    "ref_id": "HT-125486EF",
    "timestamp": "2026-06-05T18:18:07.000Z"
  },
  {
    "id": "TX-C40EF137",
    "tanggal": "2026-04-07",
    "tipe": "Pemasukan",
    "id_anggaran": 8,
    "jumlah": 220000,
    "keterangan": "Penerimaan Talangan dari Anggaran ID 13: Bayar Hutang Listrik Ke Dulloh a/n Topik",
    "ref_id": "TL-2AAD6724",
    "timestamp": "2026-06-05T18:18:47.000Z"
  },
  {
    "id": "TX-2262232C",
    "tanggal": "2026-04-07",
    "tipe": "Pengeluaran",
    "id_anggaran": 8,
    "jumlah": 220000,
    "keterangan": "Penggunaan Dana Talangan dari Anggaran ID 13: Bayar Hutang Listrik Ke Dulloh a/n Topik",
    "ref_id": "TL-2AAD6724",
    "timestamp": "2026-06-05T18:18:48.000Z"
  },
  {
    "id": "TX-B48CD64F",
    "tanggal": "2026-04-07",
    "tipe": "Pengeluaran",
    "id_anggaran": 13,
    "jumlah": 220000,
    "keterangan": "Pemberian Talangan ke Anggaran ID 8: Bayar Hutang Listrik Ke Dulloh a/n Topik",
    "ref_id": "TL-2AAD6724",
    "timestamp": "2026-06-05T18:18:48.000Z"
  },
  {
    "id": "TX-70D30DF5",
    "tanggal": "2026-04-20",
    "tipe": "Pemasukan",
    "id_anggaran": 13,
    "jumlah": 1800000,
    "keterangan": "Penerimaan Talangan dari Anggaran ID 12: Langganan Listrik dan Internet Bulan April",
    "ref_id": "TL-18559094",
    "timestamp": "2026-06-05T18:21:27.000Z"
  },
  {
    "id": "TX-02732A37",
    "tanggal": "2026-04-20",
    "tipe": "Pengeluaran",
    "id_anggaran": 13,
    "jumlah": 1800000,
    "keterangan": "Penggunaan Dana Talangan dari Anggaran ID 12: Langganan Listrik dan Internet Bulan April",
    "ref_id": "TL-18559094",
    "timestamp": "2026-06-05T18:21:28.000Z"
  },
  {
    "id": "TX-3F7F0546",
    "tanggal": "2026-04-20",
    "tipe": "Pengeluaran",
    "id_anggaran": 12,
    "jumlah": 1800000,
    "keterangan": "Pemberian Talangan ke Anggaran ID 13: Langganan Listrik dan Internet Bulan April",
    "ref_id": "TL-18559094",
    "timestamp": "2026-06-05T18:21:28.000Z"
  },
  {
    "id": "TX-972D2AEF",
    "tanggal": "2026-04-20",
    "tipe": "Pemasukan",
    "id_anggaran": 7,
    "jumlah": 250000,
    "keterangan": "Penerimaan Talangan dari Anggaran ID 13: Aldo Beberes Pasar",
    "ref_id": "TL-C3478E85",
    "timestamp": "2026-06-05T18:28:21.000Z"
  },
  {
    "id": "TX-BF0089A1",
    "tanggal": "2026-04-20",
    "tipe": "Pengeluaran",
    "id_anggaran": 7,
    "jumlah": 250000,
    "keterangan": "Penggunaan Dana Talangan dari Anggaran ID 13: Aldo Beberes Pasar",
    "ref_id": "TL-C3478E85",
    "timestamp": "2026-06-05T18:28:22.000Z"
  },
  {
    "id": "TX-16CAB5AD",
    "tanggal": "2026-04-20",
    "tipe": "Pengeluaran",
    "id_anggaran": 13,
    "jumlah": 250000,
    "keterangan": "Pemberian Talangan ke Anggaran ID 7: Aldo Beberes Pasar",
    "ref_id": "TL-C3478E85",
    "timestamp": "2026-06-05T18:28:23.000Z"
  },
  {
    "id": "TX-76947E77",
    "tanggal": "2026-05-13",
    "tipe": "Pemasukan",
    "id_anggaran": 73,
    "jumlah": 880000,
    "keterangan": "Penerimaan Talangan dari Anggaran ID 13: Konsumsi Hari Terakhir Inspektorat",
    "ref_id": "TL-9F005F42",
    "timestamp": "2026-06-05T18:34:12.000Z"
  },
  {
    "id": "TX-94FA835B",
    "tanggal": "2026-05-13",
    "tipe": "Pengeluaran",
    "id_anggaran": 73,
    "jumlah": 880000,
    "keterangan": "Penggunaan Dana Talangan dari Anggaran ID 13: Konsumsi Hari Terakhir Inspektorat",
    "ref_id": "TL-9F005F42",
    "timestamp": "2026-06-05T18:34:13.000Z"
  },
  {
    "id": "TX-EC369C82",
    "tanggal": "2026-05-13",
    "tipe": "Pengeluaran",
    "id_anggaran": 13,
    "jumlah": 880000,
    "keterangan": "Pemberian Talangan ke Anggaran ID 73: Konsumsi Hari Terakhir Inspektorat",
    "ref_id": "TL-9F005F42",
    "timestamp": "2026-06-05T18:34:13.000Z"
  },
  {
    "id": "TX-13598D7C",
    "tanggal": "2026-06-03",
    "tipe": "Pemasukan",
    "id_anggaran": 13,
    "jumlah": 1500000,
    "keterangan": "Penerimaan Talangan dari Anggaran ID 61: Listrik dan Internet Mei dan Juni",
    "ref_id": "TL-BEC4C8E9",
    "timestamp": "2026-06-05T18:39:33.000Z"
  },
  {
    "id": "TX-226D35E8",
    "tanggal": "2026-06-03",
    "tipe": "Pengeluaran",
    "id_anggaran": 13,
    "jumlah": 1500000,
    "keterangan": "Penggunaan Dana Talangan dari Anggaran ID 61: Listrik dan Internet Mei dan Juni",
    "ref_id": "TL-BEC4C8E9",
    "timestamp": "2026-06-05T18:39:33.000Z"
  },
  {
    "id": "TX-1B5E0DF4",
    "tanggal": "2026-06-03",
    "tipe": "Pengeluaran",
    "id_anggaran": 61,
    "jumlah": 1500000,
    "keterangan": "Pemberian Talangan ke Anggaran ID 13: Listrik dan Internet Mei dan Juni",
    "ref_id": "TL-BEC4C8E9",
    "timestamp": "2026-06-05T18:39:33.000Z"
  },
  {
    "id": "TX-7D603DF9",
    "tanggal": "2026-06-03",
    "tipe": "Pemasukan",
    "id_anggaran": 13,
    "jumlah": 350000,
    "keterangan": "Penerimaan Talangan dari Anggaran ID 23: Kekurangan Bayar Listrik dan Internet Bulan Mei dan Juni",
    "ref_id": "TL-9018F4DC",
    "timestamp": "2026-06-05T18:40:22.000Z"
  },
  {
    "id": "TX-9D988746",
    "tanggal": "2026-06-03",
    "tipe": "Pengeluaran",
    "id_anggaran": 13,
    "jumlah": 350000,
    "keterangan": "Penggunaan Dana Talangan dari Anggaran ID 23: Kekurangan Bayar Listrik dan Internet Bulan Mei dan Juni",
    "ref_id": "TL-9018F4DC",
    "timestamp": "2026-06-05T18:40:24.000Z"
  },
  {
    "id": "TX-1BC09C41",
    "tanggal": "2026-06-03",
    "tipe": "Pengeluaran",
    "id_anggaran": 23,
    "jumlah": 350000,
    "keterangan": "Pemberian Talangan ke Anggaran ID 13: Kekurangan Bayar Listrik dan Internet Bulan Mei dan Juni",
    "ref_id": "TL-9018F4DC",
    "timestamp": "2026-06-05T18:40:24.000Z"
  },
  {
    "id": "TX-E01CCD95",
    "tanggal": "2026-04-25",
    "tipe": "Pemasukan",
    "id_anggaran": 17,
    "jumlah": 500000,
    "keterangan": "Penerimaan Talangan dari Anggaran ID 13: Rincian \\nGanti busi 100 rb\\nGanti kabel lan baut2 150 \\nRb\\nOngkos servis 200 rb \\nUdud lan kopi 50 rb\\nTotal 500 rb",
    "ref_id": "TL-56DDADBC",
    "timestamp": "2026-06-05T18:41:26.000Z"
  },
  {
    "id": "TX-A552B71A",
    "tanggal": "2026-04-25",
    "tipe": "Pengeluaran",
    "id_anggaran": 17,
    "jumlah": 500000,
    "keterangan": "Penggunaan Dana Talangan dari Anggaran ID 13: Rincian \\nGanti busi 100 rb\\nGanti kabel lan baut2 150 \\nRb\\nOngkos servis 200 rb \\nUdud lan kopi 50 rb\\nTotal 500 rb",
    "ref_id": "TL-56DDADBC",
    "timestamp": "2026-06-05T18:41:26.000Z"
  },
  {
    "id": "TX-FF2F40F3",
    "tanggal": "2026-04-25",
    "tipe": "Pengeluaran",
    "id_anggaran": 13,
    "jumlah": 500000,
    "keterangan": "Pemberian Talangan ke Anggaran ID 17: Rincian \\nGanti busi 100 rb\\nGanti kabel lan baut2 150 \\nRb\\nOngkos servis 200 rb \\nUdud lan kopi 50 rb\\nTotal 500 rb",
    "ref_id": "TL-56DDADBC",
    "timestamp": "2026-06-05T18:41:26.000Z"
  },
  {
    "id": "TX-6D6E3ADD",
    "tanggal": "2026-03-16",
    "tipe": "Pemasukan",
    "id_anggaran": 11,
    "jumlah": 2000000,
    "keterangan": "Penerimaan Talangan dari Anggaran ID 12: Honor Kemit Bulan Februari",
    "ref_id": "TL-03C0A920",
    "timestamp": "2026-06-05T18:44:05.000Z"
  },
  {
    "id": "TX-EC539141",
    "tanggal": "2026-03-16",
    "tipe": "Pengeluaran",
    "id_anggaran": 11,
    "jumlah": 2000000,
    "keterangan": "Penggunaan Dana Talangan dari Anggaran ID 12: Honor Kemit Bulan Februari",
    "ref_id": "TL-03C0A920",
    "timestamp": "2026-06-05T18:44:05.000Z"
  },
  {
    "id": "TX-6DF6EFE8",
    "tanggal": "2026-03-16",
    "tipe": "Pengeluaran",
    "id_anggaran": 12,
    "jumlah": 2000000,
    "keterangan": "Pemberian Talangan ke Anggaran ID 11: Honor Kemit Bulan Februari",
    "ref_id": "TL-03C0A920",
    "timestamp": "2026-06-05T18:44:06.000Z"
  },
  {
    "id": "TX-BD9BC0A4",
    "tanggal": "2026-03-17",
    "tipe": "Pengeluaran",
    "id_anggaran": 12,
    "jumlah": 1000000,
    "keterangan": "Pemberian Pinjaman Hutang ke Pribadi: Darurat",
    "ref_id": "HT-CC7D62D9",
    "timestamp": "2026-06-05T18:45:38.000Z"
  },
  {
    "id": "TX-DC595037",
    "tanggal": "2026-03-17",
    "tipe": "Pengeluaran",
    "id_anggaran": 12,
    "jumlah": 4000000,
    "keterangan": "Pemberian Pinjaman Hutang ke Pribadi: Darurat",
    "ref_id": "HT-D2F7697F",
    "timestamp": "2026-06-05T18:46:09.000Z"
  },
  {
    "id": "TX-A6A49CDF",
    "tanggal": "2026-03-17",
    "tipe": "Pengeluaran",
    "id_anggaran": 12,
    "jumlah": 3000000,
    "keterangan": "Pemberian Pinjaman Hutang ke Pribadi: DARURAT",
    "ref_id": "HT-BA4AA2BD",
    "timestamp": "2026-06-05T18:46:39.000Z"
  },
  {
    "id": "TX-4838CF7B",
    "tanggal": "2026-03-17",
    "tipe": "Pemasukan",
    "id_anggaran": 67,
    "jumlah": 3700000,
    "keterangan": "Penerimaan Talangan dari Anggaran ID 12: Talangan MUI",
    "ref_id": "TL-B84C966F",
    "timestamp": "2026-06-05T18:47:11.000Z"
  },
  {
    "id": "TX-5503E31E",
    "tanggal": "2026-03-17",
    "tipe": "Pengeluaran",
    "id_anggaran": 67,
    "jumlah": 3700000,
    "keterangan": "Penggunaan Dana Talangan dari Anggaran ID 12: Talangan MUI",
    "ref_id": "TL-B84C966F",
    "timestamp": "2026-06-05T18:47:11.000Z"
  },
  {
    "id": "TX-00284ECE",
    "tanggal": "2026-03-17",
    "tipe": "Pengeluaran",
    "id_anggaran": 12,
    "jumlah": 3700000,
    "keterangan": "Pemberian Talangan ke Anggaran ID 67: Talangan MUI",
    "ref_id": "TL-B84C966F",
    "timestamp": "2026-06-05T18:47:11.000Z"
  },
  {
    "id": "TX-790420B2",
    "tanggal": "2025-04-15",
    "tipe": "Pemasukan",
    "id_anggaran": 11,
    "jumlah": 4000000,
    "keterangan": "Penerimaan Talangan dari Anggaran ID 12: Honor Kemit Maret dan April",
    "ref_id": "TL-DAFDB763",
    "timestamp": "2026-06-05T18:48:12.000Z"
  },
  {
    "id": "TX-0C48E5F1",
    "tanggal": "2025-04-15",
    "tipe": "Pengeluaran",
    "id_anggaran": 11,
    "jumlah": 4000000,
    "keterangan": "Penggunaan Dana Talangan dari Anggaran ID 12: Honor Kemit Maret dan April",
    "ref_id": "TL-DAFDB763",
    "timestamp": "2026-06-05T18:48:12.000Z"
  },
  {
    "id": "TX-95F895BC",
    "tanggal": "2025-04-15",
    "tipe": "Pengeluaran",
    "id_anggaran": 12,
    "jumlah": 4000000,
    "keterangan": "Pemberian Talangan ke Anggaran ID 11: Honor Kemit Maret dan April",
    "ref_id": "TL-DAFDB763",
    "timestamp": "2026-06-05T18:48:13.000Z"
  },
  {
    "id": "TX-70533329",
    "tanggal": "2026-04-24",
    "tipe": "Pengeluaran",
    "id_anggaran": 12,
    "jumlah": 1000000,
    "keterangan": "Pemberian Pinjaman Hutang ke Pribadi: Hutang Kuwu",
    "ref_id": "HT-B63E0F66",
    "timestamp": "2026-06-05T18:48:40.000Z"
  },
  {
    "id": "TX-B9AA52FA",
    "tanggal": "2026-06-24",
    "tipe": "Pengeluaran",
    "id_anggaran": 12,
    "jumlah": 3000000,
    "keterangan": "Pemberian Pinjaman Hutang ke Pribadi: Sekolah",
    "ref_id": "HT-144D89C7",
    "timestamp": "2026-06-05T18:49:08.000Z"
  },
  {
    "id": "TX-85B547DF",
    "tanggal": "2026-04-26",
    "tipe": "Pengeluaran",
    "id_anggaran": 12,
    "jumlah": 2000000,
    "keterangan": "Pemberian Pinjaman Hutang ke Pribadi: Hutang Ardi",
    "ref_id": "HT-63DB20B6",
    "timestamp": "2026-06-05T18:49:43.000Z"
  },
  {
    "id": "TX-33D45CC6",
    "tanggal": "2024-06-05",
    "tipe": "Pengeluaran",
    "id_anggaran": 12,
    "jumlah": 1000000,
    "keterangan": "Pemberian Pinjaman Hutang ke Pribadi: Boca Sekolah",
    "ref_id": "HT-EFC16D10",
    "timestamp": "2026-06-05T18:50:09.000Z"
  },
  {
    "id": "TX-DBE2F230",
    "tanggal": "2026-02-17",
    "tipe": "Pemasukan",
    "id_anggaran": 65,
    "jumlah": 6500000,
    "keterangan": "Penerimaan Talangan dari Anggaran ID 12: Talangi LPM",
    "ref_id": "TL-66914D27",
    "timestamp": "2026-06-05T18:51:43.000Z"
  },
  {
    "id": "TX-D0B56119",
    "tanggal": "2026-02-17",
    "tipe": "Pengeluaran",
    "id_anggaran": 65,
    "jumlah": 6500000,
    "keterangan": "Penggunaan Dana Talangan dari Anggaran ID 12: Talangi LPM",
    "ref_id": "TL-66914D27",
    "timestamp": "2026-06-05T18:51:44.000Z"
  },
  {
    "id": "TX-BB1C6584",
    "tanggal": "2026-02-17",
    "tipe": "Pengeluaran",
    "id_anggaran": 12,
    "jumlah": 6500000,
    "keterangan": "Pemberian Talangan ke Anggaran ID 65: Talangi LPM",
    "ref_id": "TL-66914D27",
    "timestamp": "2026-06-05T18:51:45.000Z"
  },
  {
    "id": "TX-B32E28C9",
    "tanggal": "2026-03-26",
    "tipe": "Pengeluaran",
    "id_anggaran": 19,
    "jumlah": 18600000,
    "keterangan": "Tunjangan BPD ADD Tahap I",
    "timestamp": "2026-06-05T18:55:24.000Z"
  },
  {
    "id": "TX-891F107C",
    "tanggal": "2026-04-28",
    "tipe": "Pengeluaran",
    "id_anggaran": 23,
    "jumlah": 5200000,
    "keterangan": "Pemberian Pinjaman Hutang ke Pribadi: Uang 10.000.000 diambil Ardi\\nyang 4.800 talangan Sampah",
    "ref_id": "HT-760C4370",
    "timestamp": "2026-06-05T18:57:18.000Z"
  },
  {
    "id": "TX-0818893A",
    "tanggal": "2026-04-30",
    "tipe": "Pengeluaran",
    "id_anggaran": 23,
    "jumlah": 2500000,
    "keterangan": "Ibu Muksinah Ibu Kalimah Ibu Amnah Bapak Rois Bapak Ino Suparno Ibu Amanah Bapak Kusnadi",
    "timestamp": "2026-06-05T18:58:46.000Z"
  },
  {
    "id": "TX-6045CDB8",
    "tanggal": "2026-05-04",
    "tipe": "Pengeluaran",
    "id_anggaran": 23,
    "jumlah": 1500000,
    "keterangan": "Dana Kematian 5 Orang (Imam Syauqi)",
    "timestamp": "2026-06-05T19:00:22.000Z"
  },
  {
    "id": "TX-277489AF",
    "tanggal": "2026-05-10",
    "tipe": "Pemasukan",
    "id_anggaran": 9,
    "jumlah": 300000,
    "keterangan": "Penerimaan Talangan dari Anggaran ID 23: Pengharum Ruangan",
    "ref_id": "TL-F21806D3",
    "timestamp": "2026-06-05T19:01:00.000Z"
  },
  {
    "id": "TX-120A1DED",
    "tanggal": "2026-05-10",
    "tipe": "Pengeluaran",
    "id_anggaran": 9,
    "jumlah": 300000,
    "keterangan": "Penggunaan Dana Talangan dari Anggaran ID 23: Pengharum Ruangan",
    "ref_id": "TL-F21806D3",
    "timestamp": "2026-06-05T19:01:00.000Z"
  },
  {
    "id": "TX-4E18D05B",
    "tanggal": "2026-05-10",
    "tipe": "Pengeluaran",
    "id_anggaran": 23,
    "jumlah": 300000,
    "keterangan": "Pemberian Talangan ke Anggaran ID 9: Pengharum Ruangan",
    "ref_id": "TL-F21806D3",
    "timestamp": "2026-06-05T19:01:01.000Z"
  },
  {
    "id": "TX-44C1F837",
    "tanggal": "2026-05-25",
    "tipe": "Pemasukan",
    "id_anggaran": 73,
    "jumlah": 1000000,
    "keterangan": "Penerimaan Talangan dari Anggaran ID 23: Samidi ( Bon Honor Pemungut Sampah)",
    "ref_id": "TL-5C446451",
    "timestamp": "2026-06-05T19:02:25.000Z"
  },
  {
    "id": "TX-574FD139",
    "tanggal": "2026-05-25",
    "tipe": "Pengeluaran",
    "id_anggaran": 73,
    "jumlah": 1000000,
    "keterangan": "Penggunaan Dana Talangan dari Anggaran ID 23: Samidi ( Bon Honor Pemungut Sampah)",
    "ref_id": "TL-5C446451",
    "timestamp": "2026-06-05T19:02:25.000Z"
  },
  {
    "id": "TX-DE1481F5",
    "tanggal": "2026-05-25",
    "tipe": "Pengeluaran",
    "id_anggaran": 23,
    "jumlah": 1000000,
    "keterangan": "Pemberian Talangan ke Anggaran ID 73: Samidi ( Bon Honor Pemungut Sampah)",
    "ref_id": "TL-5C446451",
    "timestamp": "2026-06-05T19:02:26.000Z"
  },
  {
    "id": "TX-B8363C6F",
    "tanggal": "2026-05-25",
    "tipe": "Pemasukan",
    "id_anggaran": 7,
    "jumlah": 170817,
    "keterangan": "Penerimaan Talangan dari Anggaran ID 28: ATK dll",
    "ref_id": "TL-EF98282B",
    "timestamp": "2026-06-05T19:04:54.000Z"
  },
  {
    "id": "TX-A2A86FE7",
    "tanggal": "2026-05-25",
    "tipe": "Pengeluaran",
    "id_anggaran": 7,
    "jumlah": 170817,
    "keterangan": "Penggunaan Dana Talangan dari Anggaran ID 28: ATK dll",
    "ref_id": "TL-EF98282B",
    "timestamp": "2026-06-05T19:04:54.000Z"
  },
  {
    "id": "TX-EE9F6D9E",
    "tanggal": "2026-05-25",
    "tipe": "Pengeluaran",
    "id_anggaran": 28,
    "jumlah": 170817,
    "keterangan": "Pemberian Talangan ke Anggaran ID 7: ATK dll",
    "ref_id": "TL-EF98282B",
    "timestamp": "2026-06-05T19:04:55.000Z"
  },
  {
    "id": "TX-8E2B87BA",
    "tanggal": "2026-05-06",
    "tipe": "Pengeluaran",
    "id_anggaran": 31,
    "jumlah": 37920000,
    "keterangan": "Honor RT/RW Dana Desa",
    "timestamp": "2026-06-05T19:05:54.000Z"
  },
  {
    "id": "TX-897CCCF9",
    "tanggal": "2026-04-30",
    "tipe": "Pengeluaran",
    "id_anggaran": 34,
    "jumlah": 15000000,
    "keterangan": "Pemberian Pinjaman Hutang ke Pribadi: Diambil Pakuwu",
    "ref_id": "HT-57581EB0",
    "timestamp": "2026-06-05T19:06:41.000Z"
  },
  {
    "id": "TX-5A900D48",
    "tanggal": "2026-04-28",
    "tipe": "Pengeluaran",
    "id_anggaran": 38,
    "jumlah": 14400000,
    "keterangan": "Honor TK Al-Ikhwan ( Hana)",
    "timestamp": "2026-06-05T19:07:17.000Z"
  },
  {
    "id": "TX-7CA37A3C",
    "tanggal": "2026-04-30",
    "tipe": "Pengeluaran",
    "id_anggaran": 39,
    "jumlah": 25000000,
    "keterangan": "Pemberian Pinjaman Hutang ke Pribadi: Diambil Pa Kuwu",
    "ref_id": "HT-34B378B6",
    "timestamp": "2026-06-05T19:07:57.000Z"
  },
  {
    "id": "TX-7391ABCB",
    "tanggal": "2026-05-06",
    "tipe": "Pengeluaran",
    "id_anggaran": 39,
    "jumlah": 56960000,
    "keterangan": "Poyandu ( Ibu Kuwu)",
    "timestamp": "2026-06-05T19:08:28.000Z"
  },
  {
    "id": "TX-BE028D01",
    "tanggal": "2026-04-30",
    "tipe": "Pengeluaran",
    "id_anggaran": 46,
    "jumlah": 8550000,
    "keterangan": "Pemberian Pinjaman Hutang ke Pribadi: Hutang Imam",
    "ref_id": "HT-098D2396",
    "timestamp": "2026-06-05T19:09:19.000Z"
  },
  {
    "id": "TX-59688C90",
    "tanggal": "2026-04-29",
    "tipe": "Pengeluaran",
    "id_anggaran": 46,
    "jumlah": 9450000,
    "keterangan": "Pemberian Pinjaman Hutang ke Pribadi: Hutang Ardi",
    "ref_id": "HT-C3E8A360",
    "timestamp": "2026-06-05T19:09:49.000Z"
  },
  {
    "id": "TX-0FB838DA",
    "tanggal": "2026-04-28",
    "tipe": "Pengeluaran",
    "id_anggaran": 47,
    "jumlah": 4800000,
    "keterangan": "Mob Demob : 1.500.000 Solar 150 L : 1.350.000 Swa Beco : 1.050.000 Operator : 600.000 Ivan : 300.000 uang diambil Pa kuwu",
    "timestamp": "2026-06-05T19:11:01.000Z"
  },
  {
    "id": "TX-771B0233",
    "tanggal": "2026-04-30",
    "tipe": "Pengeluaran",
    "id_anggaran": 47,
    "jumlah": 2200000,
    "keterangan": "Pemberian Pinjaman Hutang ke Pribadi: Hutang Imam",
    "ref_id": "HT-362DB932",
    "timestamp": "2026-06-05T19:11:51.000Z"
  },
  {
    "id": "TX-4CBDA64D",
    "tanggal": "2026-05-04",
    "tipe": "Pengeluaran",
    "id_anggaran": 47,
    "jumlah": 1000000,
    "keterangan": "Pemberian Pinjaman Hutang ke Pribadi: Hutang Ilham",
    "ref_id": "HT-8435D071",
    "timestamp": "2026-06-05T19:12:32.000Z"
  },
  {
    "id": "TX-3D1AC1F5",
    "tanggal": "2026-05-02",
    "tipe": "Pemasukan",
    "id_anggaran": 18,
    "jumlah": 250000,
    "keterangan": "Penerimaan Talangan dari Anggaran ID 47: Kopi Pengurasan : 50.000 Cuci Ac 2 Bh : 200.000",
    "ref_id": "TL-C6944008",
    "timestamp": "2026-06-05T19:13:56.000Z"
  },
  {
    "id": "TX-072F10A0",
    "tanggal": "2026-05-02",
    "tipe": "Pengeluaran",
    "id_anggaran": 18,
    "jumlah": 250000,
    "keterangan": "Penggunaan Dana Talangan dari Anggaran ID 47: Kopi Pengurasan : 50.000 Cuci Ac 2 Bh : 200.000",
    "ref_id": "TL-C6944008",
    "timestamp": "2026-06-05T19:13:57.000Z"
  },
  {
    "id": "TX-F50FCDF4",
    "tanggal": "2026-05-02",
    "tipe": "Pengeluaran",
    "id_anggaran": 47,
    "jumlah": 250000,
    "keterangan": "Pemberian Talangan ke Anggaran ID 18: Kopi Pengurasan : 50.000 Cuci Ac 2 Bh : 200.000",
    "ref_id": "TL-C6944008",
    "timestamp": "2026-06-05T19:13:57.000Z"
  },
  {
    "id": "TX-CA1AD858",
    "tanggal": "2026-05-25",
    "tipe": "Pemasukan",
    "id_anggaran": 7,
    "jumlah": 100000,
    "keterangan": "Penerimaan Talangan dari Anggaran ID 47: Konsumsi Bagi Honor RT/RW",
    "ref_id": "TL-F1F034D8",
    "timestamp": "2026-06-05T19:14:44.000Z"
  },
  {
    "id": "TX-BF14AD29",
    "tanggal": "2026-05-25",
    "tipe": "Pengeluaran",
    "id_anggaran": 7,
    "jumlah": 100000,
    "keterangan": "Penggunaan Dana Talangan dari Anggaran ID 47: Konsumsi Bagi Honor RT/RW",
    "ref_id": "TL-F1F034D8",
    "timestamp": "2026-06-05T19:14:44.000Z"
  },
  {
    "id": "TX-C62603B3",
    "tanggal": "2026-05-25",
    "tipe": "Pengeluaran",
    "id_anggaran": 47,
    "jumlah": 100000,
    "keterangan": "Pemberian Talangan ke Anggaran ID 7: Konsumsi Bagi Honor RT/RW",
    "ref_id": "TL-F1F034D8",
    "timestamp": "2026-06-05T19:14:45.000Z"
  },
  {
    "id": "TX-1967C3E6",
    "tanggal": "2026-05-06",
    "tipe": "Pengeluaran",
    "id_anggaran": 48,
    "jumlah": 3600000,
    "keterangan": "Honor Babinsa dan Babinkamtibmas",
    "timestamp": "2026-06-05T19:15:51.000Z"
  },
  {
    "id": "TX-BC8FC5AF",
    "tanggal": "2026-04-30",
    "tipe": "Pengeluaran",
    "id_anggaran": 49,
    "jumlah": 20000000,
    "keterangan": "Pemberian Pinjaman Hutang ke Pribadi: Diambil Pakuwu",
    "ref_id": "HT-6C601262",
    "timestamp": "2026-06-05T19:16:30.000Z"
  },
  {
    "id": "TX-E18005D3",
    "tanggal": "2026-04-30",
    "tipe": "Pengeluaran",
    "id_anggaran": 50,
    "jumlah": 5000000,
    "keterangan": "Pemberian Pinjaman Hutang ke Pribadi: Diambil Pa Kuwu",
    "ref_id": "HT-C4639758",
    "timestamp": "2026-06-05T19:17:00.000Z"
  },
  {
    "id": "TX-A8610F2F",
    "tanggal": "2026-05-04",
    "tipe": "Pengeluaran",
    "id_anggaran": 59,
    "jumlah": 4000000,
    "keterangan": "rehab masjid nurul huda imam",
    "timestamp": "2026-06-05T19:18:36.000Z"
  },
  {
    "id": "TX-2595F73E",
    "tanggal": "2026-03-15",
    "tipe": "Pemasukan",
    "id_anggaran": 73,
    "jumlah": 1700000,
    "keterangan": "Penerimaan Talangan dari Anggaran ID 60: Konsumsi Hari Pertama Inspektorat",
    "ref_id": "TL-C1770E91",
    "timestamp": "2026-06-05T19:20:07.000Z"
  },
  {
    "id": "TX-86C65409",
    "tanggal": "2026-03-15",
    "tipe": "Pengeluaran",
    "id_anggaran": 73,
    "jumlah": 1700000,
    "keterangan": "Penggunaan Dana Talangan dari Anggaran ID 60: Konsumsi Hari Pertama Inspektorat",
    "ref_id": "TL-C1770E91",
    "timestamp": "2026-06-05T19:20:08.000Z"
  },
  {
    "id": "TX-44F0A1A1",
    "tanggal": "2026-03-15",
    "tipe": "Pengeluaran",
    "id_anggaran": 60,
    "jumlah": 1700000,
    "keterangan": "Pemberian Talangan ke Anggaran ID 73: Konsumsi Hari Pertama Inspektorat",
    "ref_id": "TL-C1770E91",
    "timestamp": "2026-06-05T19:20:09.000Z"
  },
  {
    "id": "TX-A8B1B907",
    "tanggal": "2026-04-28",
    "tipe": "Pemasukan",
    "id_anggaran": 68,
    "jumlah": 5000000,
    "keterangan": "Obat-obatan Pertanian",
    "timestamp": "2026-06-05T19:25:12.000Z"
  },
  {
    "id": "TX-B692C974",
    "tanggal": "2026-05-04",
    "tipe": "Pengeluaran",
    "id_anggaran": 68,
    "jumlah": 500000,
    "keterangan": "Obat Suket Wanaiman (Kemit)",
    "timestamp": "2026-06-05T19:25:51.000Z"
  },
  {
    "id": "TX-AD80B1B4",
    "tanggal": "2026-05-06",
    "tipe": "Pemasukan",
    "id_anggaran": 9,
    "jumlah": 300000,
    "keterangan": "Penerimaan Talangan dari Anggaran ID 68: Pengharum Ruangan",
    "ref_id": "TL-4E7FDC84",
    "timestamp": "2026-06-05T19:26:27.000Z"
  },
  {
    "id": "TX-4DB5E963",
    "tanggal": "2026-05-06",
    "tipe": "Pengeluaran",
    "id_anggaran": 9,
    "jumlah": 300000,
    "keterangan": "Penggunaan Dana Talangan dari Anggaran ID 68: Pengharum Ruangan",
    "ref_id": "TL-4E7FDC84",
    "timestamp": "2026-06-05T19:26:28.000Z"
  },
  {
    "id": "TX-05D38F03",
    "tanggal": "2026-05-06",
    "tipe": "Pengeluaran",
    "id_anggaran": 68,
    "jumlah": 300000,
    "keterangan": "Pemberian Talangan ke Anggaran ID 9: Pengharum Ruangan",
    "ref_id": "TL-4E7FDC84",
    "timestamp": "2026-06-05T19:26:28.000Z"
  },
  {
    "id": "TX-B4C264C8",
    "tanggal": "2026-05-06",
    "tipe": "Pengeluaran",
    "id_anggaran": 68,
    "jumlah": 1000000,
    "keterangan": "Pemberian Pinjaman Hutang ke Pribadi: Kaminah Pas Bagi Honor RT",
    "ref_id": "HT-AC94ED03",
    "timestamp": "2026-06-05T19:27:02.000Z"
  },
  {
    "id": "TX-EE86DB18",
    "tanggal": "2026-05-06",
    "tipe": "Pemasukan",
    "id_anggaran": 7,
    "jumlah": 700000,
    "keterangan": "Penerimaan Talangan dari Anggaran ID 68: Honor Pengambilan Uang 2 x (Ardi, mamuri, Tangguh)",
    "ref_id": "TL-E38CD5FE",
    "timestamp": "2026-06-05T19:27:56.000Z"
  },
  {
    "id": "TX-FE7235E4",
    "tanggal": "2026-05-06",
    "tipe": "Pengeluaran",
    "id_anggaran": 7,
    "jumlah": 700000,
    "keterangan": "Penggunaan Dana Talangan dari Anggaran ID 68: Honor Pengambilan Uang 2 x (Ardi, mamuri, Tangguh)",
    "ref_id": "TL-E38CD5FE",
    "timestamp": "2026-06-05T19:27:56.000Z"
  },
  {
    "id": "TX-5191A311",
    "tanggal": "2026-05-06",
    "tipe": "Pengeluaran",
    "id_anggaran": 68,
    "jumlah": 700000,
    "keterangan": "Pemberian Talangan ke Anggaran ID 7: Honor Pengambilan Uang 2 x (Ardi, mamuri, Tangguh)",
    "ref_id": "TL-E38CD5FE",
    "timestamp": "2026-06-05T19:27:56.000Z"
  },
  {
    "id": "TX-6D424A4C",
    "tanggal": "2026-05-13",
    "tipe": "Pemasukan",
    "id_anggaran": 73,
    "jumlah": 2400000,
    "keterangan": "Penerimaan Talangan dari Anggaran ID 68: Inspektorat",
    "ref_id": "TL-6827CA03",
    "timestamp": "2026-06-05T19:28:55.000Z"
  },
  {
    "id": "TX-4ACED1D3",
    "tanggal": "2026-05-13",
    "tipe": "Pengeluaran",
    "id_anggaran": 73,
    "jumlah": 2400000,
    "keterangan": "Penggunaan Dana Talangan dari Anggaran ID 68: Inspektorat",
    "ref_id": "TL-6827CA03",
    "timestamp": "2026-06-05T19:28:56.000Z"
  },
  {
    "id": "TX-4BC1E852",
    "tanggal": "2026-05-13",
    "tipe": "Pengeluaran",
    "id_anggaran": 68,
    "jumlah": 2400000,
    "keterangan": "Pemberian Talangan ke Anggaran ID 73: Inspektorat",
    "ref_id": "TL-6827CA03",
    "timestamp": "2026-06-05T19:28:56.000Z"
  },
  {
    "id": "TX-576983A0",
    "tanggal": "2026-05-13",
    "tipe": "Pemasukan",
    "id_anggaran": 73,
    "jumlah": 3600000,
    "keterangan": "Penerimaan Talangan dari Anggaran ID 71: Inspektorat",
    "ref_id": "TL-5FED62E3",
    "timestamp": "2026-06-05T19:30:48.000Z"
  },
  {
    "id": "TX-83C209E7",
    "tanggal": "2026-05-13",
    "tipe": "Pengeluaran",
    "id_anggaran": 73,
    "jumlah": 3600000,
    "keterangan": "Penggunaan Dana Talangan dari Anggaran ID 71: Inspektorat",
    "ref_id": "TL-5FED62E3",
    "timestamp": "2026-06-05T19:30:48.000Z"
  },
  {
    "id": "TX-A71E41FF",
    "tanggal": "2026-05-13",
    "tipe": "Pengeluaran",
    "id_anggaran": 71,
    "jumlah": 3600000,
    "keterangan": "Pemberian Talangan ke Anggaran ID 73: Inspektorat",
    "ref_id": "TL-5FED62E3",
    "timestamp": "2026-06-05T19:30:49.000Z"
  },
  {
    "id": "TX-8ED96474",
    "tanggal": "2026-02-04",
    "tipe": "Pemasukan",
    "id_anggaran": 7,
    "jumlah": 400000,
    "keterangan": "Penerimaan Talangan dari Anggaran ID 72: Penebangan Pohon Wanaiman",
    "ref_id": "TL-52043511",
    "timestamp": "2026-06-05T19:33:06.000Z"
  },
  {
    "id": "TX-B22D22A9",
    "tanggal": "2026-02-04",
    "tipe": "Pengeluaran",
    "id_anggaran": 7,
    "jumlah": 400000,
    "keterangan": "Penggunaan Dana Talangan dari Anggaran ID 72: Penebangan Pohon Wanaiman",
    "ref_id": "TL-52043511",
    "timestamp": "2026-06-05T19:33:06.000Z"
  },
  {
    "id": "TX-EF59C6A1",
    "tanggal": "2026-02-04",
    "tipe": "Pengeluaran",
    "id_anggaran": 72,
    "jumlah": 400000,
    "keterangan": "Pemberian Talangan ke Anggaran ID 7: Penebangan Pohon Wanaiman",
    "ref_id": "TL-52043511",
    "timestamp": "2026-06-05T19:33:06.000Z"
  },
  {
    "id": "TX-AF449DF7",
    "tanggal": "2026-03-14",
    "tipe": "Pemasukan",
    "id_anggaran": 7,
    "jumlah": 800000,
    "keterangan": "Penerimaan Talangan dari Anggaran ID 72: Pupuk Lapangan Madsinah : 100.000 Stempel Mitra Cai : 100.000 Amplop Survei Mitra Cai : 400.000 Referensi Bank : 100.000 Saep ke Dinas Pertanina : 100.000",
    "ref_id": "TL-A29CE3E5",
    "timestamp": "2026-06-05T19:34:27.000Z"
  },
  {
    "id": "TX-025A35DE",
    "tanggal": "2026-03-14",
    "tipe": "Pengeluaran",
    "id_anggaran": 7,
    "jumlah": 800000,
    "keterangan": "Penggunaan Dana Talangan dari Anggaran ID 72: Pupuk Lapangan Madsinah : 100.000 Stempel Mitra Cai : 100.000 Amplop Survei Mitra Cai : 400.000 Referensi Bank : 100.000 Saep ke Dinas Pertanina : 100.000",
    "ref_id": "TL-A29CE3E5",
    "timestamp": "2026-06-05T19:34:28.000Z"
  },
  {
    "id": "TX-1F94F914",
    "tanggal": "2026-03-14",
    "tipe": "Pengeluaran",
    "id_anggaran": 72,
    "jumlah": 800000,
    "keterangan": "Pemberian Talangan ke Anggaran ID 7: Pupuk Lapangan Madsinah : 100.000 Stempel Mitra Cai : 100.000 Amplop Survei Mitra Cai : 400.000 Referensi Bank : 100.000 Saep ke Dinas Pertanina : 100.000",
    "ref_id": "TL-A29CE3E5",
    "timestamp": "2026-06-05T19:34:28.000Z"
  },
  {
    "id": "TX-6B1237F8",
    "tanggal": "2026-02-10",
    "tipe": "Pemasukan",
    "id_anggaran": 55,
    "jumlah": 300000,
    "keterangan": "Penerimaan Talangan dari Anggaran ID 72: Imtihan",
    "ref_id": "TL-A8BD7D20",
    "timestamp": "2026-06-05T19:37:03.000Z"
  },
  {
    "id": "TX-D02CA27A",
    "tanggal": "2026-02-10",
    "tipe": "Pengeluaran",
    "id_anggaran": 55,
    "jumlah": 300000,
    "keterangan": "Penggunaan Dana Talangan dari Anggaran ID 72: Imtihan",
    "ref_id": "TL-A8BD7D20",
    "timestamp": "2026-06-05T19:37:03.000Z"
  },
  {
    "id": "TX-18EB79D9",
    "tanggal": "2026-02-10",
    "tipe": "Pengeluaran",
    "id_anggaran": 72,
    "jumlah": 300000,
    "keterangan": "Pemberian Talangan ke Anggaran ID 55: Imtihan",
    "ref_id": "TL-A8BD7D20",
    "timestamp": "2026-06-05T19:37:04.000Z"
  },
  {
    "id": "TX-F2F8D1C8",
    "tanggal": "2026-02-10",
    "tipe": "Pengeluaran",
    "id_anggaran": 72,
    "jumlah": 2000000,
    "keterangan": "Pemberian Pinjaman Hutang ke Pribadi: Hutang Ardi",
    "ref_id": "HT-51FC4B9B",
    "timestamp": "2026-06-05T19:37:45.000Z"
  },
  {
    "id": "TX-5D0F7F2E",
    "tanggal": "2026-02-11",
    "tipe": "Pemasukan",
    "id_anggaran": 18,
    "jumlah": 800000,
    "keterangan": "Penerimaan Talangan dari Anggaran ID 72: Service Ac Ruanngan Pa Kuwu",
    "ref_id": "TL-C903D6B4",
    "timestamp": "2026-06-05T19:38:30.000Z"
  },
  {
    "id": "TX-8DFF6222",
    "tanggal": "2026-02-11",
    "tipe": "Pengeluaran",
    "id_anggaran": 18,
    "jumlah": 800000,
    "keterangan": "Penggunaan Dana Talangan dari Anggaran ID 72: Service Ac Ruanngan Pa Kuwu",
    "ref_id": "TL-C903D6B4",
    "timestamp": "2026-06-05T19:38:30.000Z"
  },
  {
    "id": "TX-6EE580A6",
    "tanggal": "2026-02-11",
    "tipe": "Pengeluaran",
    "id_anggaran": 72,
    "jumlah": 800000,
    "keterangan": "Pemberian Talangan ke Anggaran ID 18: Service Ac Ruanngan Pa Kuwu",
    "ref_id": "TL-C903D6B4",
    "timestamp": "2026-06-05T19:38:31.000Z"
  },
  {
    "id": "TX-5C18F290",
    "tanggal": "2026-02-12",
    "tipe": "Pemasukan",
    "id_anggaran": 8,
    "jumlah": 300000,
    "keterangan": "Penerimaan Talangan dari Anggaran ID 72: Tagihan Alat Listrik Pasar Desa Opik",
    "ref_id": "TL-DA7D69DF",
    "timestamp": "2026-06-05T19:39:15.000Z"
  },
  {
    "id": "TX-6F34FB57",
    "tanggal": "2026-02-12",
    "tipe": "Pengeluaran",
    "id_anggaran": 8,
    "jumlah": 300000,
    "keterangan": "Penggunaan Dana Talangan dari Anggaran ID 72: Tagihan Alat Listrik Pasar Desa Opik",
    "ref_id": "TL-DA7D69DF",
    "timestamp": "2026-06-05T19:39:15.000Z"
  },
  {
    "id": "TX-E94401C9",
    "tanggal": "2026-02-12",
    "tipe": "Pengeluaran",
    "id_anggaran": 72,
    "jumlah": 300000,
    "keterangan": "Pemberian Talangan ke Anggaran ID 8: Tagihan Alat Listrik Pasar Desa Opik",
    "ref_id": "TL-DA7D69DF",
    "timestamp": "2026-06-05T19:39:16.000Z"
  },
  {
    "id": "TX-FA8A01DB",
    "tanggal": "2026-02-13",
    "tipe": "Pengeluaran",
    "id_anggaran": 72,
    "jumlah": 2000000,
    "keterangan": "Pemberian Pinjaman Hutang ke Pribadi: Hutang Ibu Kuwu",
    "ref_id": "HT-D78B7DEB",
    "timestamp": "2026-06-05T19:39:49.000Z"
  },
  {
    "id": "TX-FF641A91",
    "tanggal": "2026-02-19",
    "tipe": "Pemasukan",
    "id_anggaran": 62,
    "jumlah": 350000,
    "keterangan": "Penerimaan Talangan dari Anggaran ID 72: Tarling Mushola As-Shidiqiyah",
    "ref_id": "TL-4495C986",
    "timestamp": "2026-06-05T19:41:12.000Z"
  },
  {
    "id": "TX-D32D7FE3",
    "tanggal": "2026-02-19",
    "tipe": "Pengeluaran",
    "id_anggaran": 62,
    "jumlah": 350000,
    "keterangan": "Penggunaan Dana Talangan dari Anggaran ID 72: Tarling Mushola As-Shidiqiyah",
    "ref_id": "TL-4495C986",
    "timestamp": "2026-06-05T19:41:13.000Z"
  },
  {
    "id": "TX-CB936369",
    "tanggal": "2026-02-19",
    "tipe": "Pengeluaran",
    "id_anggaran": 72,
    "jumlah": 350000,
    "keterangan": "Pemberian Talangan ke Anggaran ID 62: Tarling Mushola As-Shidiqiyah",
    "ref_id": "TL-4495C986",
    "timestamp": "2026-06-05T19:41:14.000Z"
  },
  {
    "id": "TX-1B98AABF",
    "tanggal": "2026-02-27",
    "tipe": "Pengeluaran",
    "id_anggaran": 72,
    "jumlah": 1200000,
    "keterangan": "Pemberian Pinjaman Hutang ke Pribadi: Hutang Imam",
    "ref_id": "HT-C0B5569D",
    "timestamp": "2026-06-05T19:41:48.000Z"
  },
  {
    "id": "TX-486271A4",
    "tanggal": "2026-03-31",
    "tipe": "Pengeluaran",
    "id_anggaran": 72,
    "jumlah": 500000,
    "keterangan": "Pemberian Pinjaman Hutang ke Pribadi: Upah Tukang Nyi Tosa",
    "ref_id": "HT-29397920",
    "timestamp": "2026-06-05T19:45:15.000Z"
  },
  {
    "id": "TX-A33AC6E9",
    "tanggal": "2026-03-31",
    "tipe": "Pengeluaran",
    "id_anggaran": 72,
    "jumlah": 1000000,
    "keterangan": "Pemberian Pinjaman Hutang ke Pribadi: Hutang Imam",
    "ref_id": "HT-E2FFBCA7",
    "timestamp": "2026-06-05T19:45:51.000Z"
  },
  {
    "id": "TX-6A4D9CC0",
    "tanggal": "2026-03-10",
    "tipe": "Pemasukan",
    "id_anggaran": 52,
    "jumlah": 10000000,
    "keterangan": "Penerimaan Talangan dari Anggaran ID 72: THR KE IBU KUWU",
    "ref_id": "TL-200F62E9",
    "timestamp": "2026-06-05T19:46:43.000Z"
  },
  {
    "id": "TX-0F4C7983",
    "tanggal": "2026-03-10",
    "tipe": "Pengeluaran",
    "id_anggaran": 52,
    "jumlah": 10000000,
    "keterangan": "Penggunaan Dana Talangan dari Anggaran ID 72: THR KE IBU KUWU",
    "ref_id": "TL-200F62E9",
    "timestamp": "2026-06-05T19:46:44.000Z"
  },
  {
    "id": "TX-0782F902",
    "tanggal": "2026-03-10",
    "tipe": "Pengeluaran",
    "id_anggaran": 72,
    "jumlah": 10000000,
    "keterangan": "Pemberian Talangan ke Anggaran ID 52: THR KE IBU KUWU",
    "ref_id": "TL-200F62E9",
    "timestamp": "2026-06-05T19:46:44.000Z"
  },
  {
    "id": "TX-34A8CCCF",
    "tanggal": "2026-03-02",
    "tipe": "Pengeluaran",
    "id_anggaran": 72,
    "jumlah": 1000000,
    "keterangan": "Pemberian Pinjaman Hutang ke Pribadi: UPAH TUKANG NYI TOSA",
    "ref_id": "HT-039FE7B1",
    "timestamp": "2026-06-05T19:47:29.000Z"
  },
  {
    "id": "TX-A4930CC3",
    "tanggal": "2026-02-14",
    "tipe": "Pemasukan",
    "id_anggaran": 7,
    "jumlah": 500000,
    "keterangan": "Penerimaan Talangan dari Anggaran ID 72: Bantuan Bangun Rumah Wa Nunung",
    "ref_id": "TL-EEF5A23E",
    "timestamp": "2026-06-05T19:57:14.000Z"
  },
  {
    "id": "TX-9CBE117D",
    "tanggal": "2026-02-14",
    "tipe": "Pengeluaran",
    "id_anggaran": 7,
    "jumlah": 500000,
    "keterangan": "Penggunaan Dana Talangan dari Anggaran ID 72: Bantuan Bangun Rumah Wa Nunung",
    "ref_id": "TL-EEF5A23E",
    "timestamp": "2026-06-05T19:57:15.000Z"
  },
  {
    "id": "TX-0D9FCF2E",
    "tanggal": "2026-02-14",
    "tipe": "Pengeluaran",
    "id_anggaran": 72,
    "jumlah": 500000,
    "keterangan": "Pemberian Talangan ke Anggaran ID 7: Bantuan Bangun Rumah Wa Nunung",
    "ref_id": "TL-EEF5A23E",
    "timestamp": "2026-06-05T19:57:16.000Z"
  },
  {
    "id": "TX-11F40D04",
    "tanggal": "2026-03-02",
    "tipe": "Pemasukan",
    "id_anggaran": 9,
    "jumlah": 300000,
    "keterangan": "Penerimaan Talangan dari Anggaran ID 72: Pengharum Ruangan",
    "ref_id": "TL-CD312A86",
    "timestamp": "2026-06-05T19:59:51.000Z"
  },
  {
    "id": "TX-ACF91B94",
    "tanggal": "2026-03-02",
    "tipe": "Pengeluaran",
    "id_anggaran": 9,
    "jumlah": 300000,
    "keterangan": "Penggunaan Dana Talangan dari Anggaran ID 72: Pengharum Ruangan",
    "ref_id": "TL-CD312A86",
    "timestamp": "2026-06-05T19:59:52.000Z"
  },
  {
    "id": "TX-120363A0",
    "tanggal": "2026-03-02",
    "tipe": "Pengeluaran",
    "id_anggaran": 72,
    "jumlah": 300000,
    "keterangan": "Pemberian Talangan ke Anggaran ID 9: Pengharum Ruangan",
    "ref_id": "TL-CD312A86",
    "timestamp": "2026-06-05T19:59:52.000Z"
  },
  {
    "id": "TX-F49E7CC3",
    "tanggal": "2026-06-02",
    "tipe": "Pemasukan",
    "id_anggaran": 13,
    "jumlah": 2000000,
    "keterangan": "Penerimaan Talangan dari Anggaran ID 12: Langganan Listrik dan Internet Mei Juni",
    "ref_id": "TL-548BE3E0",
    "timestamp": "2026-06-05T20:01:50.000Z"
  },
  {
    "id": "TX-9D90585A",
    "tanggal": "2026-06-02",
    "tipe": "Pengeluaran",
    "id_anggaran": 13,
    "jumlah": 2000000,
    "keterangan": "Penggunaan Dana Talangan dari Anggaran ID 12: Langganan Listrik dan Internet Mei Juni",
    "ref_id": "TL-548BE3E0",
    "timestamp": "2026-06-05T20:01:50.000Z"
  },
  {
    "id": "TX-73F2CF78",
    "tanggal": "2026-06-02",
    "tipe": "Pengeluaran",
    "id_anggaran": 12,
    "jumlah": 2000000,
    "keterangan": "Pemberian Talangan ke Anggaran ID 13: Langganan Listrik dan Internet Mei Juni",
    "ref_id": "TL-548BE3E0",
    "timestamp": "2026-06-05T20:01:51.000Z"
  },
  {
    "id": "TX-D5A07F7B",
    "tanggal": "2026-05-05",
    "tipe": "Pengeluaran",
    "id_anggaran": 11,
    "jumlah": 2000000,
    "keterangan": "Honor Kemit Bulan Mei",
    "timestamp": "2026-06-05T20:03:54.000Z"
  },
  {
    "id": "TX-68E435D8",
    "tanggal": "2026-01-17",
    "tipe": "Pemasukan",
    "id_anggaran": 73,
    "jumlah": 1000000,
    "keterangan": "Penerimaan Talangan dari Anggaran ID 4: Kekurangan Tahsinula Ahlaq",
    "ref_id": "TL-006ADFE1",
    "timestamp": "2026-06-05T20:09:25.000Z"
  },
  {
    "id": "TX-CC01F90F",
    "tanggal": "2026-01-17",
    "tipe": "Pengeluaran",
    "id_anggaran": 73,
    "jumlah": 1000000,
    "keterangan": "Penggunaan Dana Talangan dari Anggaran ID 4: Kekurangan Tahsinula Ahlaq",
    "ref_id": "TL-006ADFE1",
    "timestamp": "2026-06-05T20:09:26.000Z"
  },
  {
    "id": "TX-40B3A54F",
    "tanggal": "2026-01-17",
    "tipe": "Pengeluaran",
    "id_anggaran": 4,
    "jumlah": 1000000,
    "keterangan": "Pemberian Talangan ke Anggaran ID 73: Kekurangan Tahsinula Ahlaq",
    "ref_id": "TL-006ADFE1",
    "timestamp": "2026-06-05T20:09:27.000Z"
  },
  {
    "id": "TX-14AA3B5B",
    "tanggal": "2025-06-03",
    "tipe": "Pemasukan",
    "id_anggaran": 73,
    "jumlah": 200000,
    "keterangan": "Penerimaan Talangan dari Anggaran ID 23: Bensin Samidi Antar Jagung ke H. Ade",
    "ref_id": "TL-840B1905",
    "timestamp": "2026-06-05T20:13:43.000Z"
  },
  {
    "id": "TX-D6D2D100",
    "tanggal": "2025-06-03",
    "tipe": "Pengeluaran",
    "id_anggaran": 73,
    "jumlah": 200000,
    "keterangan": "Penggunaan Dana Talangan dari Anggaran ID 23: Bensin Samidi Antar Jagung ke H. Ade",
    "ref_id": "TL-840B1905",
    "timestamp": "2026-06-05T20:13:44.000Z"
  },
  {
    "id": "TX-03E869B7",
    "tanggal": "2025-06-03",
    "tipe": "Pengeluaran",
    "id_anggaran": 23,
    "jumlah": 200000,
    "keterangan": "Pemberian Talangan ke Anggaran ID 73: Bensin Samidi Antar Jagung ke H. Ade",
    "ref_id": "TL-840B1905",
    "timestamp": "2026-06-05T20:13:45.000Z"
  },
  {
    "id": "TX-C8D93234",
    "tanggal": "2026-06-05",
    "tipe": "Pemasukan",
    "id_anggaran": 68,
    "jumlah": 150000,
    "keterangan": "Penerimaan Talangan dari Anggaran ID 23: Obat Kompos Pa Yogi",
    "ref_id": "TL-16DFAF57",
    "timestamp": "2026-06-05T20:27:10.000Z"
  },
  {
    "id": "TX-5B583822",
    "tanggal": "2026-06-05",
    "tipe": "Pengeluaran",
    "id_anggaran": 68,
    "jumlah": 150000,
    "keterangan": "Penggunaan Dana Talangan dari Anggaran ID 23: Obat Kompos Pa Yogi",
    "ref_id": "TL-16DFAF57",
    "timestamp": "2026-06-05T20:27:11.000Z"
  },
  {
    "id": "TX-6384890A",
    "tanggal": "2026-06-05",
    "tipe": "Pengeluaran",
    "id_anggaran": 23,
    "jumlah": 150000,
    "keterangan": "Pemberian Talangan ke Anggaran ID 68: Obat Kompos Pa Yogi",
    "ref_id": "TL-16DFAF57",
    "timestamp": "2026-06-05T20:27:12.000Z"
  },
  {
    "id": "TX-08F60B68",
    "tanggal": "2026-06-05",
    "tipe": "Pemasukan",
    "id_anggaran": 68,
    "jumlah": 43600,
    "keterangan": "Penerimaan Talangan dari Anggaran ID 47: Obat Kompos Pa yogi",
    "ref_id": "TL-DA6AA5AC",
    "timestamp": "2026-06-05T20:27:54.000Z"
  },
  {
    "id": "TX-6000DB71",
    "tanggal": "2026-06-05",
    "tipe": "Pengeluaran",
    "id_anggaran": 68,
    "jumlah": 43600,
    "keterangan": "Penggunaan Dana Talangan dari Anggaran ID 47: Obat Kompos Pa yogi",
    "ref_id": "TL-DA6AA5AC",
    "timestamp": "2026-06-05T20:27:55.000Z"
  },
  {
    "id": "TX-0475499E",
    "tanggal": "2026-06-05",
    "tipe": "Pengeluaran",
    "id_anggaran": 47,
    "jumlah": 43600,
    "keterangan": "Pemberian Talangan ke Anggaran ID 68: Obat Kompos Pa yogi",
    "ref_id": "TL-DA6AA5AC",
    "timestamp": "2026-06-05T20:27:55.000Z"
  },
  {
    "id": "TX-CF77994A",
    "tanggal": "2026-06-05",
    "tipe": "Pemasukan",
    "id_anggaran": 68,
    "jumlah": 300000,
    "keterangan": "Penerimaan Talangan dari Anggaran ID 60: Obat Kompos Pa yogi",
    "ref_id": "TL-406BAA09",
    "timestamp": "2026-06-05T20:28:47.000Z"
  },
  {
    "id": "TX-E312BE1F",
    "tanggal": "2026-06-05",
    "tipe": "Pengeluaran",
    "id_anggaran": 68,
    "jumlah": 300000,
    "keterangan": "Penggunaan Dana Talangan dari Anggaran ID 60: Obat Kompos Pa yogi",
    "ref_id": "TL-406BAA09",
    "timestamp": "2026-06-05T20:28:47.000Z"
  },
  {
    "id": "TX-4164E0FF",
    "tanggal": "2026-06-05",
    "tipe": "Pengeluaran",
    "id_anggaran": 60,
    "jumlah": 300000,
    "keterangan": "Pemberian Talangan ke Anggaran ID 68: Obat Kompos Pa yogi",
    "ref_id": "TL-406BAA09",
    "timestamp": "2026-06-05T20:28:48.000Z"
  },
  {
    "id": "TX-925456BF",
    "tanggal": "2026-06-05",
    "tipe": "Pengeluaran",
    "id_anggaran": 68,
    "jumlah": 100000,
    "keterangan": "Obat Kompos Pa Yogi",
    "timestamp": "2026-06-05T20:29:26.000Z"
  },
  {
    "id": "TX-5C0910B3",
    "tanggal": "2026-06-05",
    "tipe": "Pemasukan",
    "id_anggaran": 73,
    "jumlah": 87000,
    "keterangan": "Penerimaan Talangan dari Anggaran ID 13: Konsumsi Tamu kecamatan Pak Amrin",
    "ref_id": "TL-A4085233",
    "timestamp": "2026-06-05T20:30:35.000Z"
  },
  {
    "id": "TX-9332EAF7",
    "tanggal": "2026-06-05",
    "tipe": "Pengeluaran",
    "id_anggaran": 73,
    "jumlah": 87000,
    "keterangan": "Penggunaan Dana Talangan dari Anggaran ID 13: Konsumsi Tamu kecamatan Pak Amrin",
    "ref_id": "TL-A4085233",
    "timestamp": "2026-06-05T20:30:36.000Z"
  },
  {
    "id": "TX-9E40237C",
    "tanggal": "2026-06-05",
    "tipe": "Pengeluaran",
    "id_anggaran": 13,
    "jumlah": 87000,
    "keterangan": "Pemberian Talangan ke Anggaran ID 73: Konsumsi Tamu kecamatan Pak Amrin",
    "ref_id": "TL-A4085233",
    "timestamp": "2026-06-05T20:30:37.000Z"
  }
];

export const INITIAL_TALANGAN: Talangan[] = [
  {
    "id": "TL-C97CE0AD",
    "tanggal": "2026-01-17",
    "id_anggaran_pemberi": 4,
    "id_anggaran_penerima": 60,
    "jumlah": 2000000,
    "keterangan": "Rehab Mushola Tahsinul Ahlaq",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T17:20:21.000Z"
  },
  {
    "id": "TL-6A32993C",
    "tanggal": "2026-03-26",
    "id_anggaran_pemberi": 13,
    "id_anggaran_penerima": 7,
    "jumlah": 430000,
    "keterangan": "ATK ( Kertas, Pulpen, Map, Tinta, Dll)",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T18:08:25.000Z"
  },
  {
    "id": "TL-3EAEAC12",
    "tanggal": "2026-03-28",
    "id_anggaran_pemberi": 13,
    "id_anggaran_penerima": 7,
    "jumlah": 1500000,
    "keterangan": "ATK",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T18:09:30.000Z"
  },
  {
    "id": "TL-DF000F9A",
    "tanggal": "2026-01-04",
    "id_anggaran_pemberi": 13,
    "id_anggaran_penerima": 47,
    "jumlah": 700000,
    "keterangan": "Solar Beco (Saep)",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T18:12:15.000Z"
  },
  {
    "id": "TL-68121E8E",
    "tanggal": "2026-04-01",
    "id_anggaran_pemberi": 13,
    "id_anggaran_penerima": 45,
    "jumlah": 1300000,
    "keterangan": "Pengurugan Pasar Desa",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T18:14:01.000Z"
  },
  {
    "id": "TL-A8F269A9",
    "tanggal": "2026-04-01",
    "id_anggaran_pemberi": 13,
    "id_anggaran_penerima": 9,
    "jumlah": 300000,
    "keterangan": "Pengharum Ruangan",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T18:16:09.000Z"
  },
  {
    "id": "TL-2AAD6724",
    "tanggal": "2026-04-07",
    "id_anggaran_pemberi": 13,
    "id_anggaran_penerima": 8,
    "jumlah": 220000,
    "keterangan": "Bayar Hutang Listrik Ke Dulloh a/n Topik",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T18:18:47.000Z"
  },
  {
    "id": "TL-18559094",
    "tanggal": "2026-04-20",
    "id_anggaran_pemberi": 12,
    "id_anggaran_penerima": 13,
    "jumlah": 1800000,
    "keterangan": "Langganan Listrik dan Internet Bulan April",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T18:21:27.000Z"
  },
  {
    "id": "TL-C3478E85",
    "tanggal": "2026-04-20",
    "id_anggaran_pemberi": 13,
    "id_anggaran_penerima": 7,
    "jumlah": 250000,
    "keterangan": "Aldo Beberes Pasar",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T18:28:20.000Z"
  },
  {
    "id": "TL-9F005F42",
    "tanggal": "2026-05-13",
    "id_anggaran_pemberi": 13,
    "id_anggaran_penerima": 73,
    "jumlah": 880000,
    "keterangan": "Konsumsi Hari Terakhir Inspektorat",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T18:34:11.000Z"
  },
  {
    "id": "TL-BEC4C8E9",
    "tanggal": "2026-06-03",
    "id_anggaran_pemberi": 61,
    "id_anggaran_penerima": 13,
    "jumlah": 1500000,
    "keterangan": "Listrik dan Internet Mei dan Juni",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T18:39:32.000Z"
  },
  {
    "id": "TL-9018F4DC",
    "tanggal": "2026-06-03",
    "id_anggaran_pemberi": 23,
    "id_anggaran_penerima": 13,
    "jumlah": 350000,
    "keterangan": "Kekurangan Bayar Listrik dan Internet Bulan Mei dan Juni",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T18:40:22.000Z"
  },
  {
    "id": "TL-56DDADBC",
    "tanggal": "2026-04-25",
    "id_anggaran_pemberi": 13,
    "id_anggaran_penerima": 17,
    "jumlah": 500000,
    "keterangan": "Rincian \nGanti busi 100 rb\nGanti kabel lan baut2 150 \nRb\nOngkos servis 200 rb \nUdud lan kopi 50 rb\nTotal 500 rb",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T18:41:25.000Z"
  },
  {
    "id": "TL-03C0A920",
    "tanggal": "2026-03-16",
    "id_anggaran_pemberi": 12,
    "id_anggaran_penerima": 11,
    "jumlah": 2000000,
    "keterangan": "Honor Kemit Bulan Februari",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T18:44:04.000Z"
  },
  {
    "id": "TL-B84C966F",
    "tanggal": "2026-03-17",
    "id_anggaran_pemberi": 12,
    "id_anggaran_penerima": 67,
    "jumlah": 3700000,
    "keterangan": "Talangan MUI",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T18:47:10.000Z"
  },
  {
    "id": "TL-DAFDB763",
    "tanggal": "2025-04-15",
    "id_anggaran_pemberi": 12,
    "id_anggaran_penerima": 11,
    "jumlah": 4000000,
    "keterangan": "Honor Kemit Maret dan April",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T18:48:11.000Z"
  },
  {
    "id": "TL-66914D27",
    "tanggal": "2026-02-17",
    "id_anggaran_pemberi": 12,
    "id_anggaran_penerima": 65,
    "jumlah": 6500000,
    "keterangan": "Talangi LPM",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T18:51:43.000Z"
  },
  {
    "id": "TL-F21806D3",
    "tanggal": "2026-05-10",
    "id_anggaran_pemberi": 23,
    "id_anggaran_penerima": 9,
    "jumlah": 300000,
    "keterangan": "Pengharum Ruangan",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T19:00:59.000Z"
  },
  {
    "id": "TL-5C446451",
    "tanggal": "2026-05-25",
    "id_anggaran_pemberi": 23,
    "id_anggaran_penerima": 73,
    "jumlah": 1000000,
    "keterangan": "Samidi ( Bon Honor Pemungut Sampah)",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T19:02:24.000Z"
  },
  {
    "id": "TL-EF98282B",
    "tanggal": "2026-05-25",
    "id_anggaran_pemberi": 28,
    "id_anggaran_penerima": 7,
    "jumlah": 170817,
    "keterangan": "ATK dll",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T19:04:52.000Z"
  },
  {
    "id": "TL-C6944008",
    "tanggal": "2026-05-02",
    "id_anggaran_pemberi": 47,
    "id_anggaran_penerima": 18,
    "jumlah": 250000,
    "keterangan": "Kopi Pengurasan : 50.000 Cuci Ac 2 Bh : 200.000",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T19:13:55.000Z"
  },
  {
    "id": "TL-F1F034D8",
    "tanggal": "2026-05-25",
    "id_anggaran_pemberi": 47,
    "id_anggaran_penerima": 7,
    "jumlah": 100000,
    "keterangan": "Konsumsi Bagi Honor RT/RW",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T19:14:43.000Z"
  },
  {
    "id": "TL-C1770E91",
    "tanggal": "2026-03-15",
    "id_anggaran_pemberi": 60,
    "id_anggaran_penerima": 73,
    "jumlah": 1700000,
    "keterangan": "Konsumsi Hari Pertama Inspektorat",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T19:20:06.000Z"
  },
  {
    "id": "TL-4E7FDC84",
    "tanggal": "2026-05-06",
    "id_anggaran_pemberi": 68,
    "id_anggaran_penerima": 9,
    "jumlah": 300000,
    "keterangan": "Pengharum Ruangan",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T19:26:27.000Z"
  },
  {
    "id": "TL-E38CD5FE",
    "tanggal": "2026-05-06",
    "id_anggaran_pemberi": 68,
    "id_anggaran_penerima": 7,
    "jumlah": 700000,
    "keterangan": "Honor Pengambilan Uang 2 x (Ardi, mamuri, Tangguh)",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T19:27:55.000Z"
  },
  {
    "id": "TL-6827CA03",
    "tanggal": "2026-05-13",
    "id_anggaran_pemberi": 68,
    "id_anggaran_penerima": 73,
    "jumlah": 2400000,
    "keterangan": "Inspektorat",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T19:28:55.000Z"
  },
  {
    "id": "TL-5FED62E3",
    "tanggal": "2026-05-13",
    "id_anggaran_pemberi": 71,
    "id_anggaran_penerima": 73,
    "jumlah": 3600000,
    "keterangan": "Inspektorat",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T19:30:47.000Z"
  },
  {
    "id": "TL-52043511",
    "tanggal": "2026-02-04",
    "id_anggaran_pemberi": 72,
    "id_anggaran_penerima": 7,
    "jumlah": 400000,
    "keterangan": "Penebangan Pohon Wanaiman",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T19:33:05.000Z"
  },
  {
    "id": "TL-A29CE3E5",
    "tanggal": "2026-03-14",
    "id_anggaran_pemberi": 72,
    "id_anggaran_penerima": 7,
    "jumlah": 800000,
    "keterangan": "Pupuk Lapangan Madsinah : 100.000 Stempel Mitra Cai : 100.000 Amplop Survei Mitra Cai : 400.000 Referensi Bank : 100.000 Saep ke Dinas Pertanina : 100.000",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T19:34:26.000Z"
  },
  {
    "id": "TL-A8BD7D20",
    "tanggal": "2026-02-10",
    "id_anggaran_pemberi": 72,
    "id_anggaran_penerima": 55,
    "jumlah": 300000,
    "keterangan": "Imtihan",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T19:37:02.000Z"
  },
  {
    "id": "TL-C903D6B4",
    "tanggal": "2026-02-11",
    "id_anggaran_pemberi": 72,
    "id_anggaran_penerima": 18,
    "jumlah": 800000,
    "keterangan": "Service Ac Ruanngan Pa Kuwu",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T19:38:29.000Z"
  },
  {
    "id": "TL-DA7D69DF",
    "tanggal": "2026-02-12",
    "id_anggaran_pemberi": 72,
    "id_anggaran_penerima": 8,
    "jumlah": 300000,
    "keterangan": "Tagihan Alat Listrik Pasar Desa Opik",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T19:39:14.000Z"
  },
  {
    "id": "TL-4495C986",
    "tanggal": "2026-02-19",
    "id_anggaran_pemberi": 72,
    "id_anggaran_penerima": 62,
    "jumlah": 350000,
    "keterangan": "Tarling Mushola As-Shidiqiyah",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T19:41:12.000Z"
  },
  {
    "id": "TL-200F62E9",
    "tanggal": "2026-03-10",
    "id_anggaran_pemberi": 72,
    "id_anggaran_penerima": 52,
    "jumlah": 10000000,
    "keterangan": "THR KE IBU KUWU",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T19:46:42.000Z"
  },
  {
    "id": "TL-EEF5A23E",
    "tanggal": "2026-02-14",
    "id_anggaran_pemberi": 72,
    "id_anggaran_penerima": 7,
    "jumlah": 500000,
    "keterangan": "Bantuan Bangun Rumah Wa Nunung",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T19:57:14.000Z"
  },
  {
    "id": "TL-CD312A86",
    "tanggal": "2026-03-02",
    "id_anggaran_pemberi": 72,
    "id_anggaran_penerima": 9,
    "jumlah": 300000,
    "keterangan": "Pengharum Ruangan",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T19:59:51.000Z"
  },
  {
    "id": "TL-548BE3E0",
    "tanggal": "2026-06-02",
    "id_anggaran_pemberi": 12,
    "id_anggaran_penerima": 13,
    "jumlah": 2000000,
    "keterangan": "Langganan Listrik dan Internet Mei Juni",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T20:01:49.000Z"
  },
  {
    "id": "TL-006ADFE1",
    "tanggal": "2026-01-17",
    "id_anggaran_pemberi": 4,
    "id_anggaran_penerima": 73,
    "jumlah": 1000000,
    "keterangan": "Kekurangan Tahsinula Ahlaq",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T20:09:25.000Z"
  },
  {
    "id": "TL-840B1905",
    "tanggal": "2025-06-03",
    "id_anggaran_pemberi": 23,
    "id_anggaran_penerima": 73,
    "jumlah": 200000,
    "keterangan": "Bensin Samidi Antar Jagung ke H. Ade",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T20:13:43.000Z"
  },
  {
    "id": "TL-16DFAF57",
    "tanggal": "2026-06-05",
    "id_anggaran_pemberi": 23,
    "id_anggaran_penerima": 68,
    "jumlah": 150000,
    "keterangan": "Obat Kompos Pa Yogi",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T20:27:10.000Z"
  },
  {
    "id": "TL-DA6AA5AC",
    "tanggal": "2026-06-05",
    "id_anggaran_pemberi": 47,
    "id_anggaran_penerima": 68,
    "jumlah": 43600,
    "keterangan": "Obat Kompos Pa yogi",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T20:27:54.000Z"
  },
  {
    "id": "TL-406BAA09",
    "tanggal": "2026-06-05",
    "id_anggaran_pemberi": 60,
    "id_anggaran_penerima": 68,
    "jumlah": 300000,
    "keterangan": "Obat Kompos Pa yogi",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T20:28:46.000Z"
  },
  {
    "id": "TL-A4085233",
    "tanggal": "2026-06-05",
    "id_anggaran_pemberi": 13,
    "id_anggaran_penerima": 73,
    "jumlah": 87000,
    "keterangan": "Konsumsi Tamu kecamatan Pak Amrin",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T20:30:34.000Z"
  }
];

export const INITIAL_HUTANG: Hutang[] = [
  {
    "id": "HT-15C54FC4",
    "tanggal": "2026-01-17",
    "id_anggaran_pemberi": 4,
    "peminjam": "IMAM",
    "jumlah": 1500000,
    "keterangan": "Keperluan Mendadak",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T17:17:47.000Z"
  },
  {
    "id": "HT-6B4B4596",
    "tanggal": "2026-01-17",
    "id_anggaran_pemberi": 4,
    "peminjam": "ARDI",
    "jumlah": 1000000,
    "keterangan": "Keperluan Mendadak",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T17:19:09.000Z"
  },
  {
    "id": "HT-C62B693D",
    "tanggal": "2026-01-14",
    "id_anggaran_pemberi": 4,
    "peminjam": "RIO (KUWU)",
    "jumlah": 45000000,
    "keterangan": "-",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T17:24:44.000Z"
  },
  {
    "id": "HT-A35E4CBF",
    "tanggal": "2026-01-17",
    "id_anggaran_pemberi": 4,
    "peminjam": "CEPAK",
    "jumlah": 475000,
    "keterangan": "Upah TUKANG Nyi Tosa",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T17:26:42.000Z"
  },
  {
    "id": "HT-9E5F126E",
    "tanggal": "2026-01-17",
    "id_anggaran_pemberi": 4,
    "peminjam": "KAMINAH",
    "jumlah": 1000000,
    "keterangan": "Darurat",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T17:27:09.000Z"
  },
  {
    "id": "HT-125486EF",
    "tanggal": "2026-04-01",
    "id_anggaran_pemberi": 13,
    "peminjam": "KUWU",
    "jumlah": 3500000,
    "keterangan": "Dana Mendesak",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T18:18:07.000Z"
  },
  {
    "id": "HT-CC7D62D9",
    "tanggal": "2026-03-17",
    "id_anggaran_pemberi": 12,
    "peminjam": "IMAM",
    "jumlah": 1000000,
    "keterangan": "Darurat",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T18:45:37.000Z"
  },
  {
    "id": "HT-D2F7697F",
    "tanggal": "2026-03-17",
    "id_anggaran_pemberi": 12,
    "peminjam": "ARDI",
    "jumlah": 4000000,
    "keterangan": "Darurat",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T18:46:08.000Z"
  },
  {
    "id": "HT-BA4AA2BD",
    "tanggal": "2026-03-17",
    "id_anggaran_pemberi": 12,
    "peminjam": "ILHAM",
    "jumlah": 3000000,
    "keterangan": "DARURAT",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T18:46:38.000Z"
  },
  {
    "id": "HT-B63E0F66",
    "tanggal": "2026-04-24",
    "id_anggaran_pemberi": 12,
    "peminjam": "KUWU",
    "jumlah": 1000000,
    "keterangan": "Hutang Kuwu",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T18:48:39.000Z"
  },
  {
    "id": "HT-144D89C7",
    "tanggal": "2026-06-24",
    "id_anggaran_pemberi": 12,
    "peminjam": "IMAM",
    "jumlah": 3000000,
    "keterangan": "Sekolah",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T18:49:07.000Z"
  },
  {
    "id": "HT-63DB20B6",
    "tanggal": "2026-04-26",
    "id_anggaran_pemberi": 12,
    "peminjam": "ARDI",
    "jumlah": 2000000,
    "keterangan": "Hutang Ardi",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T18:49:42.000Z"
  },
  {
    "id": "HT-EFC16D10",
    "tanggal": "2024-06-05",
    "id_anggaran_pemberi": 12,
    "peminjam": "IMAM",
    "jumlah": 1000000,
    "keterangan": "Boca Sekolah",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T18:50:08.000Z"
  },
  {
    "id": "HT-760C4370",
    "tanggal": "2026-04-28",
    "id_anggaran_pemberi": 23,
    "peminjam": "KUWU",
    "jumlah": 5200000,
    "keterangan": "Uang 10.000.000 diambil Ardi\\nyang 4.800 talangan Sampah",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T18:57:17.000Z"
  },
  {
    "id": "HT-57581EB0",
    "tanggal": "2026-04-30",
    "id_anggaran_pemberi": 34,
    "peminjam": "KUWU",
    "jumlah": 15000000,
    "keterangan": "Diambil Pakuwu",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T19:06:39.000Z"
  },
  {
    "id": "HT-34B378B6",
    "tanggal": "2026-04-30",
    "id_anggaran_pemberi": 39,
    "peminjam": "KUWU",
    "jumlah": 25000000,
    "keterangan": "Diambil Pa Kuwu",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T19:07:57.000Z"
  },
  {
    "id": "HT-098D2396",
    "tanggal": "2026-04-30",
    "id_anggaran_pemberi": 46,
    "peminjam": "IMAM",
    "jumlah": 8550000,
    "keterangan": "Hutang Imam",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T19:09:18.000Z"
  },
  {
    "id": "HT-C3E8A360",
    "tanggal": "2026-04-29",
    "id_anggaran_pemberi": 46,
    "peminjam": "ARDI",
    "jumlah": 9450000,
    "keterangan": "Hutang Ardi",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T19:09:48.000Z"
  },
  {
    "id": "HT-362DB932",
    "tanggal": "2026-04-30",
    "id_anggaran_pemberi": 47,
    "peminjam": "IMAM",
    "jumlah": 2200000,
    "keterangan": "Hutang Imam",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T19:11:50.000Z"
  },
  {
    "id": "HT-8435D071",
    "tanggal": "2026-05-04",
    "id_anggaran_pemberi": 47,
    "peminjam": "ILHAM",
    "jumlah": 1000000,
    "keterangan": "Hutang Ilham",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T19:12:32.000Z"
  },
  {
    "id": "HT-6C601262",
    "tanggal": "2026-04-30",
    "id_anggaran_pemberi": 49,
    "peminjam": "KUWU",
    "jumlah": 20000000,
    "keterangan": "Diambil Pakuwu",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T19:16:29.000Z"
  },
  {
    "id": "HT-C4639758",
    "tanggal": "2026-04-30",
    "id_anggaran_pemberi": 50,
    "peminjam": "KUWU",
    "jumlah": 5000000,
    "keterangan": "Diambil Pa Kuwu",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T19:17:00.000Z"
  },
  {
    "id": "HT-AC94ED03",
    "tanggal": "2026-05-06",
    "id_anggaran_pemberi": 68,
    "peminjam": "KAMINAH",
    "jumlah": 1000000,
    "keterangan": "Kaminah Pas Bagi Honor RT",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T19:27:01.000Z"
  },
  {
    "id": "HT-51FC4B9B",
    "tanggal": "2026-02-10",
    "id_anggaran_pemberi": 72,
    "peminjam": "ARDI",
    "jumlah": 2000000,
    "keterangan": "Hutang Ardi",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T19:37:44.000Z"
  },
  {
    "id": "HT-D78B7DEB",
    "tanggal": "2026-02-13",
    "id_anggaran_pemberi": 72,
    "peminjam": "IBU KUWU",
    "jumlah": 2000000,
    "keterangan": "Hutang Ibu Kuwu",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T19:39:48.000Z"
  },
  {
    "id": "HT-C0B5569D",
    "tanggal": "2026-02-27",
    "id_anggaran_pemberi": 72,
    "peminjam": "IMAM",
    "jumlah": 1200000,
    "keterangan": "Hutang Imam",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T19:41:47.000Z"
  },
  {
    "id": "HT-29397920",
    "tanggal": "2026-03-31",
    "id_anggaran_pemberi": 72,
    "peminjam": "CEPAK",
    "jumlah": 500000,
    "keterangan": "Upah Tukang Nyi Tosa",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T19:45:15.000Z"
  },
  {
    "id": "HT-E2FFBCA7",
    "tanggal": "2026-03-31",
    "id_anggaran_pemberi": 72,
    "peminjam": "IMAM",
    "jumlah": 1000000,
    "keterangan": "Hutang Imam",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T19:45:51.000Z"
  },
  {
    "id": "HT-039FE7B1",
    "tanggal": "2026-03-02",
    "id_anggaran_pemberi": 72,
    "peminjam": "CEPAK",
    "jumlah": 1000000,
    "keterangan": "UPAH TUKANG NYI TOSA",
    "status": "Belum Lunas",
    "tanggal_lunas": "",
    "timestamp": "2026-06-05T19:47:29.000Z"
  }
];
